load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "atomic_batch_dispatcher",
    srcs = ["AtomicBatchDispatcher.cpp"],
    headers = ["AtomicBatchDispatcher.h"],
    use_raw_headers = True,
    deps = [
        "fbsource//third-party/fmt:fmt",
    ],
)
