load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("../../defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "atomic_batch_dispatcher",
    srcs = [
        "AtomicBatchDispatcher.cpp",
    ],
    raw_headers = [
        "AtomicBatchDispatcher.h",
    ],
    deps = [
        "//xplat/folly:format",
    ],
)

# !!!! fbcode/folly/fibers/detail/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "atomic_batch_dispatcher",
    srcs = ["AtomicBatchDispatcher.cpp"],
    headers = ["AtomicBatchDispatcher.h"],
    deps = [
        "fbsource//third-party/fmt:fmt",
    ],
)
