load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "exception_abi",
    headers = ["ExceptionAbi.h"],
    exported_deps = [
        "//folly/debugging/exception_tracer:exception_abi",
    ],
)

cpp_library(
    name = "exception_counter",
    headers = ["ExceptionCounterLib.h"],
    link_whole = True,
    exported_deps = [
        "//folly/debugging/exception_tracer:exception_counter",
    ],
)

cpp_library(
    name = "exception_tracer",
    headers = [],
    link_whole = True,
    exported_deps = [
        "//folly/debugging/exception_tracer:exception_tracer",
    ],
)

cpp_library(
    name = "exception_tracer_base",
    headers = ["ExceptionTracer.h"],
    exported_deps = [
        "//folly/debugging/exception_tracer:exception_tracer_base",
    ],
)

cpp_library(
    name = "exception_tracer_callbacks",
    headers = ["ExceptionTracerLib.h"],
    link_whole = True,
    exported_deps = [
        "//folly/debugging/exception_tracer:exception_tracer_callbacks",
    ],
)

cpp_library(
    name = "stacktrace",
    headers = ["StackTrace.h"],
    exported_deps = [
        "//folly/debugging/exception_tracer:stacktrace",
    ],
)

cpp_library(
    name = "smart_exception_tracer_singleton",
    headers = [
        "SmartExceptionTracerSingleton.h",
    ],
    exported_deps = [
        "//folly/debugging/exception_tracer:smart_exception_tracer_singleton",
    ],
)

cpp_library(
    name = "smart_exception_stack_trace_hooks",
    link_whole = True,
    deps = [
        "//folly/debugging/exception_tracer:smart_exception_stack_trace_hooks",
    ],
)

cpp_library(
    name = "smart_exception_tracer",
    headers = ["SmartExceptionTracer.h"],
    exported_deps = [
        "//folly/debugging/exception_tracer:smart_exception_tracer",
    ],
)
