load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "random_seed_test",
    srcs = ["RandomSeedTest.cpp"],
    headers = [],
    deps = [
        "//folly:portability",
        "//folly/hash/detail:random_seed",
        "//folly/portability:gtest",
        "//folly/test:test_utils",
    ],
)
