load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fbcode_entropy_wardens_folly")

python_library(
    name = "run_scenario_lib",
    srcs = [
        "checkpoint.py",
        "checkpoint_accounting.py",
        "debrief_tables.py",
        "run_scenario.py",
    ],
)
