load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fbcode_entropy_wardens_folly")

python_library(
    name = "run_scenario_lib",
    srcs = [
        "checkpoint.py",
        "checkpoint_accounting.py",
        "compress_checkpoint_outputs.py",
        "debrief_tables.py",
        "run_scenario.py",
    ],
    resources = {
        "fbcode//folly/agents/scripts:apply_diffs": "folly/agents/scripts/apply_diffs",
    },
)
