load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "async_socket_observer_interface",
    headers = ["AsyncSocketObserverInterface.h"],
    use_raw_headers = True,
    exported_deps = [
        "//folly:cpp_attributes",
        "//folly:glog",
        "//folly:optional",
        "//folly/io/async:write_flags",
    ],
)

fb_dirsync_cpp_library(
    name = "async_socket_observer_container",
    headers = ["AsyncSocketObserverContainer.h"],
    use_raw_headers = True,
    exported_deps = [
        ":async_socket_observer_interface",
        "//folly:observer_container",
    ],
)
