load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "atomic_read_mostly_main_ptr",
    srcs = [
        "AtomicReadMostlyMainPtr.cpp",
    ],
    headers = [
        "AtomicReadMostlyMainPtr.h",
    ],
    deps = [
        "//folly/executors:inline_executor",
    ],
    exported_deps = [
        "//folly:indestructible",
        "//folly/experimental:read_mostly_shared_ptr",
        "//folly/synchronization:rcu",
    ],
)

cpp_library(
    name = "read_mostly_shared_ptr",
    headers = ["ReadMostlySharedPtr.h"],
    exported_deps = [
        "//folly:function",
        "//folly/experimental:tl_ref_count",
    ],
)
