load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "inline_function_ref_test",
    srcs = [
        "InlineFunctionRefTest.cpp",
    ],
    deps = [
        "//folly/portability:gtest",
        "//folly/synchronization/detail:inline_function_ref",
    ],
)

cpp_unittest(
    name = "hardware_test",
    srcs = [
        "HardwareTest.cpp",
    ],
    deps = [
        "//folly/portability:gtest",
        "//folly/synchronization/detail:hardware",
    ],
    external_deps = [
        "glog",
    ],
)
