load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "phase_test",
    srcs = ["PhaseTest.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:singleton",
        "//folly/init:phase",
        "//folly/portability:gtest",
    ],
)
