load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "phase_test",
    srcs = ["PhaseTest.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:singleton",
        "//folly/init:phase",
        "//folly/portability:gtest",
    ],
)
