# See the documentation for more information:
# https://packit.dev/docs/configuration

specfile_path: folly.spec

upstream_package_name: folly
downstream_package_name: folly

actions:
  post-upstream-clone: "bash -c \"git clone -b packit https://pagure.io/meta/folly.git folly-dist-git && mv folly-dist-git/folly*.{spec,patch} .\""

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-development-aarch64
    - fedora-development-armhfp
    - fedora-development-i386
    - fedora-development-x86_64
    - fedora-35-aarch64
    - fedora-35-armhfp
    - fedora-35-i386
    - fedora-35-x86_64

- job: copr_build
  trigger: release
  metadata:
    targets:
    - fedora-development-aarch64
    - fedora-development-armhfp
    - fedora-development-i386
    - fedora-development-x86_64
    - fedora-35-aarch64
    - fedora-35-armhfp
    - fedora-35-i386
    - fedora-35-x86_64
