load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "atomic_grow_array_test",
    srcs = ["atomic_grow_array_test.cpp"],
    deps = [
        "//folly/concurrency/container:atomic_grow_array",
        "//folly/lang:keep",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "relaxed_concurrent_priority_queue_test",
    srcs = ["RelaxedConcurrentPriorityQueueTest.cpp"],
    headers = [],
    deps = [
        "//folly:random",
        "//folly:spin_lock",
        "//folly/experimental:flat_combining_priority_queue",
        "//folly/experimental:relaxed_concurrent_priority_queue",
        "//folly/portability:gflags",
        "//folly/portability:gtest",
        "//folly/test:deterministic_schedule",
    ],
    external_deps = [
        "glog",
        ("boost", None, "boost_thread"),
    ],
)

cpp_unittest(
    name = "lock_free_ring_buffer_test",
    srcs = ["LockFreeRingBufferTest.cpp"],
    headers = [],
    deps = [
        "//folly/concurrency/container:lock_free_ring_buffer",
        "//folly/portability:gtest",
        "//folly/test:deterministic_schedule",
    ],
)
