load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load(
    "../../defs.bzl",
    "folly_xplat_library",
)

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "observer_manager",
    srcs = [
        "Core.cpp",
        "ObserverManager.cpp",
    ],
    headers = [
        "Core.h",
        "ObserverManager.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:exception_string",
        "//folly:format",
        "//folly:range",
        "//folly:singleton",
        "//folly/concurrency:unbounded_queue",
        "//folly/portability:gflags",
        "//folly/system:thread_name",
    ],
    exported_deps = [
        "//folly:function",
        "//folly:portability",
        "//folly:synchronized",
        "//folly/experimental/observer/detail:graph_cycle_detector",
        "//folly/fibers:core_manager",
        "//folly/functional:invoke",
        "//folly/futures:core",
        "//folly/synchronization:sanitize_thread",
    ],
    exported_external_deps = [
        "glog",
    ],
)

fb_dirsync_cpp_library(
    name = "graph_cycle_detector",
    headers = ["GraphCycleDetector.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_external_deps = [
        "glog",
    ],
)
