load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "pick_task_wrapper_test",
    srcs = [
        "PickTaskWrapperTest.cpp",
    ],
    deps = [
        "//folly:portability",
        "//folly/coro:value_or_fatal",
        "//folly/coro/detail:pick_task_wrapper",
        "//folly/coro/safe:now_task",
        "//folly/coro/safe:safe_task",
        "//folly/portability:gtest",
    ],
)
