# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

config_setting(
    name = "linux-fedora",
    constraint_values = [
        "prelude//os/constraints:linux",
        "//os/linux/distro/constraints:fedora",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "linux-ubuntu",
    constraint_values = [
        "prelude//os/constraints:linux",
        "//os/linux/distro/constraints:ubuntu",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "macos-homebrew",
    constraint_values = [
        "prelude//os/constraints:macos",
    ],
    visibility = ["PUBLIC"],
)
