load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load("../../../defs.bzl", "folly_xplat_cxx_library")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "async_closure",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["AsyncClosure.h"],
    exported_deps = [
        ":async_closure_bindings",
        "//xplat/folly/coro:noexcept",
        "//xplat/folly/coro/safe:safe_task",
        "//xplat/folly/detail:tuple",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "async_closure",
    headers = ["AsyncClosure.h"],
    exported_deps = [
        ":async_closure_bindings",
        "//folly/coro:noexcept",
        "//folly/coro/safe:safe_task",
        "//folly/detail:tuple",
    ],
)

###

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "async_closure_bindings",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["AsyncClosureBindings.h"],
    exported_deps = [
        "//xplat/folly/coro/safe:captures",
        "//xplat/folly/coro/safe:safe_alias",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "async_closure_bindings",
    headers = ["AsyncClosureBindings.h"],
    exported_deps = [
        "//folly/coro/safe:captures",
        "//folly/coro/safe:safe_alias",
    ],
)

###

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "define_movable_deep_const_lref_copyable",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["DefineMovableDeepConstLrefCopyable.h"],
)

fbcode_target(
    _kind = cpp_library,
    name = "define_movable_deep_const_lref_copyable",
    headers = ["DefineMovableDeepConstLrefCopyable.h"],
)
