load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load("../defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["test_ext.h"],
)

# !!!! fbcode/folly/ext/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    headers = ["test_ext.h"],
)
