load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("../defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    headers = ["test_ext.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
)
