load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_benchmark.bzl", "fb_dirsync_cpp_benchmark")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "exception_counter_test",
    srcs = ["ExceptionCounterTest.cpp"],
    deps = [
        "//folly/debugging/exception_tracer:exception_counter",
        "//folly/debugging/exception_tracer:exception_counter_static_registration",  # @manual
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_library(
    name = "exception_tracer_benchmark_main",
    srcs = ["ExceptionTracerBenchmark.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:benchmark",
        "//folly/debugging/exception_tracer:exception_tracer_base",
        "//folly/portability:gflags",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "exception_tracer_base_benchmark",
    deps = [
        ":exception_tracer_benchmark_main",  # @manual
    ],
)

fb_dirsync_cpp_benchmark(
    name = "exception_tracer_benchmark",
    deps = [
        ":exception_tracer_benchmark_main",  # @manual
        "//folly/debugging/exception_tracer:exception_tracer",  # @manual  # @manual
    ],
)

fb_dirsync_cpp_library(
    name = "exception_tracer_test_main",
    srcs = ["ExceptionTracerTest.cpp"],
    deps = [
        "//folly/debugging/exception_tracer:exception_tracer_base",
    ],
)

fbcode_target(
    _kind = cpp_binary,
    name = "exception_tracer_base_test",
    deps = [
        ":exception_tracer_test_main",  # @manual
    ],
)

fbcode_target(
    _kind = cpp_binary,
    name = "exception_tracer_test",
    deps = [
        ":exception_tracer_test_main",  # @manual
        "//folly/debugging/exception_tracer:exception_tracer",  # @manual  # @manual
    ],
)

fbcode_target(
    _kind = cpp_unittest,
    name = "smart_exception_tracer_test",
    srcs = ["SmartExceptionTracerTest.cpp"],
    deps = [
        "//folly/coro:blocking_wait",
        "//folly/coro:task",
        "//folly/debugging/exception_tracer:smart_exception_stack_trace_hooks",  # @manual
        "//folly/debugging/exception_tracer:smart_exception_tracer",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "smart_exception_tracer_benchmark",
    srcs = ["SmartExceptionTracerBenchmark.cpp"],
    deps = [
        "//folly:benchmark",
        "//folly:exception_wrapper",
        "//folly/debugging/exception_tracer:smart_exception_stack_trace_hooks",  # @manual
        "//folly/debugging/exception_tracer:smart_exception_tracer",
    ],
)

fbcode_target(
    _kind = cpp_binary,
    name = "exception_tracer_uncaught_test_bin",
    srcs = ["ExceptionTracerUncaughtTest.cpp"],
    deps = [
        "//folly/debugging/exception_tracer:exception_tracer",  # @manual
    ],
)

fbcode_target(
    _kind = python_unittest,
    name = "exception_tracer_uncaught_test",
    srcs = ["exception_tracer_uncaught_test.py"],
    env = {
        "EXCEPTION_TRACER_TEST_BIN": "$(location :exception_tracer_uncaught_test_bin)",
    },
)
