load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load(
    "../defs.bzl",
    "folly_xplat_library",
)

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "basic_interfaces",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = [
        "Nullable.h",
        "Regular.h",
    ],
    deps = [
        "//xplat/folly:poly",
    ],
)

# !!!! fbcode/folly/poly/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "basic_interfaces",
    headers = [
        "Nullable.h",
        "Regular.h",
    ],
    exported_deps = [
        "//folly:poly",
    ],
)
