buildscript = []

[platform_fixup.'cfg(all(target_os = "windows", target_env = "gnu"))']
version = "=0.48.0"
[[platform_fixup.'cfg(all(target_os = "windows", target_env = "gnu"))'.buildscript]]
[platform_fixup.'cfg(all(target_os = "windows", target_env = "gnu"))'.buildscript.prebuilt_cxx_library]
name = "libwindows"
static_libs = ["lib/libwindows.0.48.0.a"]
