load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    # @lint-ignore BUCKLINT
    link_whole = True,
    deps = [
        "//folly/ext:test_ext",
        "//folly/io:fs_util",
        "//folly/json:dynamic",
    ],
    external_deps = [
        ("boost", None, "boost_filesystem"),
    ],
)
