load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    # @fb-only[end= ]: autodeps_keep = True,
    # @lint-ignore BUCKLINT
    link_whole = True,
    deps = [
        "//folly/experimental/io:fs_util",
        "//folly/ext:test_ext",
        "//folly/json:dynamic",
    ],
    external_deps = [
        ("boost", None, "boost_filesystem"),
    ],
)
