load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    feature = triage_InfrastructureSupermoduleOptou,
    link_whole = True,
    deps = ["//xplat/folly:dynamic"],
    exported_deps = [
        "//third-party/boost:boost_filesystem",
        "//xplat/folly:experimental_io_fs_util",
        "//xplat/folly:json",
        "//xplat/folly/ext:test_ext",
    ],
)

# !!!! fbcode/folly/ext/buck2/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "test_ext",
    srcs = ["test_ext.cpp"],
    # @fb-only[end= ]: autodeps_keep = True,
    # @lint-ignore BUCKLINT
    link_whole = True,
    deps = [
        "//folly/experimental/io:fs_util",
        "//folly/ext:test_ext",
        "//folly/json:dynamic",
    ],
    external_deps = [
        ("boost", None, "boost_filesystem"),
    ],
)
