load("@fbsource//tools/build_defs:fb_python_library.bzl", "fb_python_library")

oncall("fbcode_entropy_wardens_folly")

fb_python_library(
    # @autodeps-skip
    name = "co_bt",
    srcs = ["co_bt.py"],
    visibility = ["PUBLIC"],
)
