load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "socket_file_descriptor_map",
    srcs = ["SocketFileDescriptorMap.cpp"],
    headers = ["SocketFileDescriptorMap.h"],
    use_raw_headers = True,
    exported_deps = [
        "//folly/portability:windows",
    ],
)
