load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load(
    "../../defs.bzl",
    "folly_xplat_library",
)

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "socket_file_descriptor_map",
    srcs = [
        "SocketFileDescriptorMap.cpp",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = [
        "SocketFileDescriptorMap.h",
    ],
    deps = [
        "//xplat/folly:portability_windows",
    ],
)

# !!!! fbcode/folly/net/detail/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "socket_file_descriptor_map",
    srcs = ["SocketFileDescriptorMap.cpp"],
    headers = ["SocketFileDescriptorMap.h"],
    exported_deps = [
        "//folly/portability:windows",
    ],
)
