load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "socket_file_descriptor_map",
    srcs = ["SocketFileDescriptorMap.cpp"],
    headers = ["SocketFileDescriptorMap.h"],
    exported_deps = [
        "//folly/portability:windows",
    ],
)
