load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "array_demo",
    srcs = ["array.cpp"],
    headers = [],
    deps = [
        "//folly/json:dynamic",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "object_demo",
    srcs = ["object.cpp"],
    headers = [],
    deps = [
        "//folly/json:dynamic",
        "//folly/portability:gtest",
    ],
)
