load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

# xplat build rules

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "lib",
    srcs = [
        "lib.cpp",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = [
        "lib.h",
    ],
    deps = [
        "fbsource//xplat/folly/logging:logging",
        "//xplat/folly:range",
    ],
)

# fbcode build rules

fbcode_target(
    _kind = cpp_binary,
    name = "example",
    srcs = ["main.cpp"],
    deps = [
        ":lib",
        "//folly/init:init",
        "//folly/logging:init",
        "//folly/logging:logging",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "lib",
    srcs = ["lib.cpp"],
    headers = ["lib.h"],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:range",
        "//folly/logging:logging",
    ],
)
