load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cython_library.bzl", "CYTHON_DEFAULT_APPLE_SDKS", "CYTHON_DEFAULT_PLATFORMS", "cython_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_rule.bzl", "fb_dirsync_rule")
load("../defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "gil_aware_manual_executor",
    srcs = ["GILAwareManualExecutor.cpp"],
    headers = ["GILAwareManualExecutor.h"],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        ":weak",
        "//folly:scope_guard",
    ],
    exported_deps = [
        "//folly/executors:drivable_executor",
        "//folly/executors:sequenced_executor",
    ],
)

fb_dirsync_rule(
    name = "range",
    headers = ["range.pxd"],
    cpp_deps = [
        "//folly:range",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":folly",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "async_generator_lib",
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    raw_headers = [
        "async_generator.h",
    ],
    deps = [
        "//xplat/folly:portability",
        "//xplat/folly/experimental/coro:async_generator",
        "//xplat/folly/experimental/coro:task",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "proactor_executor",
    srcs = [
        "ProactorExecutor.cpp",
    ],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    raw_headers = [
        "ProactorExecutor.h",
    ],
    exported_deps = [
        "fbsource//third-party/python:python",
        "//xplat/folly/concurrency:concurrent_hash_map",
        "//xplat/folly/python:asyncio_executor",
    ],
)

fb_dirsync_rule(
    name = "executor",
    srcs = ["executor.pyx"],
    headers = [
        "executor.pxd",
        "executor_detail.pxd",
    ],
    header_namespace = "folly/python",
    cpp_deps = [
        "//folly/portability:unistd",
        ":asyncio_executor",
        ":executor_lib",
        ":proactor_executor",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":folly",
    ],
)

fb_dirsync_cpp_library(
    name = "futures_lib",
    headers = [
        "futures.h",
    ],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":asyncio_executor",
        ":executor_lib",
        ":weak",
        "//folly:executor",
        "//folly/futures:core",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "executor_lib",
    srcs = [
        "executor.cpp",
    ],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    raw_headers = [
        "executor.h",
    ],
    deps = [
        ":asyncio_executor",
        ":import",
        ":weak",
        "//xplat/folly:executor",
    ],
)

fb_dirsync_rule(
    name = "coro",
    headers = ["coro.pxd"],
    cpp_deps = [
        "//folly:cancellation_token",
        ":coro_lib",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":executor",
    ],
)

fb_dirsync_cpp_library(
    name = "asyncio_executor",
    srcs = [
        "AsyncioExecutor.cpp",
    ],
    headers = [
        "AsyncioExecutor.h",
    ],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":weak",
        "//folly:chrono",
        "//folly:exception_string",
        "//folly:function",
        "//folly/executors:drivable_executor",
        "//folly/executors:sequenced_executor",
        "//folly/io/async:async_base",
        "//folly/portability:gflags",
    ],
)

fb_dirsync_rule(
    name = "folly",
    headers = ["__init__.pxd"],
    cpp_deps = [
        "//folly/futures:core",
        "//folly:exception_wrapper",
        "//folly:executor",
        "//folly:portability",
        "//folly:try",
        "//folly:unit",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
)

fb_dirsync_rule(
    name = "fibers",
    srcs = ["fiber_manager.pyx"],
    headers = [
        "fiber_manager.pxd",
        "fibers.pxd",
    ],
    cpp_deps = [
        "//folly/fibers:core",
        "//folly/fibers:executor_loop_controller",
        "//folly/fibers:loop_controller",
        ":fibers_lib",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":folly",
        ":futures",
    ],
)

fb_dirsync_rule(
    name = "async_generator",
    headers = ["async_generator.pxd"],
    cpp_deps = [
        ":async_generator_lib",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":coro",
        ":optional",
    ],
)

fb_dirsync_cpp_library(
    name = "import",
    headers = [
        "import.h",
    ],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        ":error",
        "//folly:likely",
        "//folly:portability",
    ],
)

fb_dirsync_rule(
    name = "memory",
    headers = ["memory.pxd"],
    cpp_deps = [
        "//folly:memory",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
)

fb_dirsync_rule(
    name = "function",
    headers = ["function.pxd"],
    cpp_deps = [
        "//folly:function",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":folly",
    ],
)

fb_dirsync_cpp_library(
    name = "iobuf_ext",
    srcs = ["iobuf_ext.cpp"],
    headers = ["iobuf_ext.h"],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        ":weak",
    ],
    exported_deps = [
        "fbsource//third-party/python:python",
        "//folly:executor",
        "//folly/io:iobuf",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "iobuf_lib",
    srcs = ["iobuf.cpp"],
    exported_headers = {
        "folly/python/iobuf.h": "iobuf.h",
        "folly/python/iobuf_api.h": ":iobuf__iobuf_api.h",
    },
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    deps = [
        ":import",
    ],
    exported_deps = [
        "fbsource//third-party/python:python",
        "fbsource//xplat/folly/io:iobuf",
    ],
)

fb_dirsync_rule(
    name = "iobuf",
    srcs = ["iobuf.pyx"],
    headers = [
        "iobuf.pxd",
    ],
    header_namespace = "folly/python",
    api = ["iobuf"],
    cpp_deps = [
        "//folly/io:iobuf",
        ":iobuf_ext",
        ":iobuf_lib",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    tests = [
        "//folly/python/test:iobuf",
    ],
    types = ["iobuf.pyi"],
    visibility = ["PUBLIC"],
    deps = [
        ":executor",
        ":folly",
        ":futures",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "coro_lib",
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    raw_headers = [
        "coro.h",
    ],
    deps = [
        ":asyncio_executor",
        ":executor_lib",
        ":weak",
        "//xplat/folly:cancellation_token",
        "//xplat/folly:executor",
        "//xplat/folly:portability",
        "//xplat/folly/experimental/coro:task",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "fibers_lib",
    srcs = ["fibers.cpp"],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    raw_headers = ["fibers.h"],
    deps = [
        ":import",
        ":weak",
        "//xplat/folly/fibers:core",
    ],
)

fb_dirsync_rule(
    name = "cast",
    headers = ["cast.pxd"],
    cpp_deps = [
        "//folly/lang:cast",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
)

fb_dirsync_rule(
    name = "expected",
    headers = ["expected.pxd"],
    cpp_deps = ["//folly:expected"],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":folly",
    ],
)

fb_dirsync_rule(
    name = "futures",
    headers = ["futures.pxd"],
    cpp_deps = [
        ":futures_lib",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":executor",
    ],
)

fb_dirsync_cpp_library(
    name = "error",
    srcs = ["error.cpp"],
    headers = ["error.h"],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    platforms = CYTHON_DEFAULT_PLATFORMS,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        ":weak",
        "//folly:conv",
        "//folly:scope_guard",
    ],
    exported_deps = [
        "//folly:range",
    ],
)

fb_dirsync_rule(
    name = "optional",
    headers = ["optional.pxd"],
    cpp_deps = ["//folly:optional"],
    fbcode_rule = cython_library,
    package = "folly",
    visibility = ["PUBLIC"],
    deps = [
        ":folly",  # So we don't squash the "folly" package
    ],
)

fb_dirsync_rule(
    name = "fbstring",
    headers = ["fbstring.pxd"],
    cpp_deps = [
        "//folly:fbstring",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    deps = [
        ":folly",
    ],
)

fb_dirsync_rule(
    name = "request_context",
    srcs = ["request_context.pyx"],
    headers = [
        "request_context.h",
        "request_context.pxd",
    ],
    header_namespace = "folly/python",
    compatible_with = [
        "ovr_config//os:linux",
        "ovr_config//os:macos",
        "ovr_config//os:windows",
    ],
    cpp_compiler_flags = select({
        "DEFAULT": ["-DFOLLY_PYTHON_META_BUILD"],
        # Conda is not Meta Python
        "ovr_config//distro:conda": [],
    }),
    cpp_deps = [
        "//folly/io/async:request_context",
        ":weak",
    ],
    fbcode_rule = cython_library,
    package = "folly",
    types = ["request_context.pyi"],
    deps = [
        ":folly",
    ],
)

# !!!! fbcode/folly/python/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "executor_lib",
    srcs = [
        "executor.cpp",
    ],
    headers = [
        "executor.h",
    ],
    compiler_flags = select({
        "DEFAULT": [],
        "ovr_config//os:windows": [
            "-DFOLLY_PYTHON_WIN_SHAREDLIB",
        ],
    }),
    preferred_linkage = select({
        "DEFAULT": None,
        "ovr_config//os:windows": "shared",
    }),
    deps = [
        ":import",
    ],
    exported_deps = [
        ":asyncio_executor",
        ":weak",
        "//folly:executor",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "proactor_executor",
    srcs = [
        "ProactorExecutor.cpp",
    ],
    headers = [
        "ProactorExecutor.h",
    ],
    exported_deps = [
        ":asyncio_executor",
        "//folly/concurrency:concurrent_hash_map",
        "//folly/portability:windows",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "coro_lib",
    headers = [
        "coro.h",
    ],
    exported_deps = [
        ":asyncio_executor",
        ":executor_lib",
        ":weak",
        "//folly:cancellation_token",
        "//folly:executor",
        "//folly:portability",
        "//folly/coro:task",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "fibers_lib",
    srcs = ["fibers.cpp"],
    headers = ["fibers.h"],
    compiler_flags = select({
        "DEFAULT": [],
        "ovr_config//os:windows": [
            "-DFOLLY_PYTHON_WIN_SHAREDLIB",
        ],
    }),
    preferred_linkage = select({
        "DEFAULT": None,
        "ovr_config//os:windows": "shared",
    }),
    target_compatible_with = ["fbcode//opensource/macros:broken-in-oss"],
    deps = [
        ":import",
    ],
    exported_deps = [
        ":weak",
        "//folly/fibers:core",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "iobuf_lib",
    srcs = ["iobuf.cpp"],
    headers = [
        "iobuf.h",
        # @fb-only[end= ]: ":iobuf__iobuf_api.h",
    ],
    # TODO(T36778537): Cython-generated `*_api.h` headers aren't modular.
    modular_headers = False,
    target_compatible_with = ["fbcode//opensource/macros:broken-in-oss"],
    deps = [
        ":import",
    ],
    exported_deps = [
        "fbsource//third-party/python:python",  # Python.h
        "//folly/io:iobuf",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "async_generator_lib",
    headers = [
        "async_generator.h",
    ],
    exported_deps = [
        "//folly:portability",
        "//folly/coro:async_generator",
        "//folly/coro:task",
    ],
)

fbcode_target(
    _kind = cython_library,
    name = "build_mode",
    srcs = [
        "build_mode.pyx",
    ],
    package = "folly",
    types = [
        "build_mode.pyi",
    ],
    deps = [
        ":folly",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "scoped_gil_release",
    headers = [
        "ScopedGILRelease.h",
    ],
    visibility = ["PUBLIC"],
    exported_deps = [
        ":weak",
    ],
)

fb_dirsync_cpp_library(
    name = "weak",
    headers = [
        "Weak.h",
    ],
    apple_sdks = CYTHON_DEFAULT_APPLE_SDKS,
    exported_linker_flags = select({
        "DEFAULT": [],
        # These make it so linking libpython is optional
        "ovr_config//os:macos": [
            "-Xlinker",
            "-undefined",
            "-Xlinker",
            "dynamic_lookup",
        ],
    }),
    platforms = CYTHON_DEFAULT_PLATFORMS,
    tests = [
        "fbcode//folly/python/test:weak-test",
        "fbcode//folly/python/test:weak-test-linked",
    ],
    use_raw_headers = True,
    visibility = ["PUBLIC"],
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "fbsource//third-party/python:python-headers",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:windows": [
            "fbsource//third-party/python:python",  # @manual
        ],
    }),
)
