load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

# xplat build rules

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "debug",
    raw_headers = [
        "Debug.h",
    ],
    exported_deps = ["//xplat/folly/debugging/symbolizer/detail:debug"],
)

# fbcode build rules

fbcode_target(
    _kind = cpp_library,
    name = "debug",
    headers = [
        "Debug.h",
    ],
    exported_deps = [
        "//folly/debugging/symbolizer/detail:debug",
    ],
)
