load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_library,
    name = "debug",
    headers = [
        "Debug.h",
    ],
    exported_deps = [
        "//folly/debugging/symbolizer/detail:debug",
    ],
)
