load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "bits_benchmark",
    srcs = ["BitsBenchmark.cpp"],
    headers = [],
    deps = [
        "//folly:benchmark",
        "//folly/experimental:bits",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "bits_test",
    srcs = ["BitsTest.cpp"],
    headers = [],
    deps = [
        "//folly/experimental:bits",
        "//folly/portability:gflags",
        "//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)

cpp_library(
    name = "coding_test_utils",
    srcs = ["CodingTestUtils.cpp"],
    headers = ["CodingTestUtils.h"],
    deps = [
        "//folly/portability:gflags",
    ],
    exported_deps = [
        "//folly:benchmark",
        "//folly:likely",
        "//folly:optional",
        "//folly/experimental:instructions",
        "//folly/portability:gtest",
    ],
    exported_external_deps = [
        "glog",
    ],
)

cpp_unittest(
    name = "hhwheel_timer_high_res_test",
    srcs = ["HHWheelTimerHighResTest.cpp"],
    headers = [],
    deps = [
        "//folly/experimental:timerfd",
        "//folly/io/async:async_base",
        "//folly/io/async/test:util",
        "//folly/portability:gtest",
    ],
)

cpp_binary(
    name = "hhwheel_timer_high_res_benchmark",
    srcs = ["HHWheelTimerHighResBenchmark.cpp"],
    headers = [],
    deps = [
        "//folly:benchmark",
        "//folly/experimental:timerfd",
        "//folly/io/async/test:util",
    ],
)

cpp_binary(
    name = "nested_command_line_app_example",
    srcs = ["NestedCommandLineAppExample.cpp"],
    headers = [],
    deps = [
        "//folly:scope_guard",
        "//folly:string",
        "//folly/cli:program_options",
    ],
)
