load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("rust_libraries")

fbcode_target(
    _kind = rust_library,
    name = "folly",
    srcs = ["lib.rs"],
    deps = [
        "//folly/rust/string:string",
    ],
)
