load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:native_rules.bzl", "alias")
load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("rust_libraries")

fbcode_target(
    _kind = alias,
    name = "iobuf",
    actual = "fbsource//xplat/folly/rust/iobuf:iobuf",
)

fbcode_target(
    _kind = alias,
    name = "request_context_future",
    actual = "//folly/rust/request_context:request_context_future",
)

fbcode_target(
    _kind = rust_library,
    name = "folly",
    srcs = ["lib.rs"],
    deps = [
        "//folly/rust/string:string",
    ],
)
