load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_cxx_test")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_cxx_test,
    name = "async_fd_socket_test",
    srcs = ["AsyncFdSocketTest.cpp"],
    contacts = ["oncall+thrift@xmail.facebook.com"],
    deps = [
        "//xplat/folly:portability_gmock",
        "//xplat/folly:portability_gtest",
        "//xplat/folly/io/async/fdsock:async_fd_socket",
        "//xplat/folly/io/async/test:async_socket_test_lib",
    ],
)

# !!!! fbcode/folly/io/async/fdsock/test/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_unittest,
    name = "async_fd_socket_test",
    srcs = ["AsyncFdSocketTest.cpp"],
    supports_static_listing = False,
    deps = [
        "//folly/io/async/fdsock:async_fd_socket",
        "//folly/io/async/test:async_socket_test_lib",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
