load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "debug",
    srcs = ["Debug.cpp"],
    headers = ["Debug.h"],
    use_raw_headers = True,
    deps = [
        "fbsource//third-party/glibc:dl",
        "//folly:portability",
    ],
)
