load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

# xplat build rules

fb_dirsync_cpp_library(
    name = "settings",
    headers = [
        "Settings.h",
        "detail/SettingsImpl.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/settings:settings",
    ],
)

# fbcode build rules

fbcode_target(
    _kind = cpp_library,
    name = "types",
    headers = [
        "Types.h",
    ],
    exported_deps = [
        "//folly/settings:types",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "immutables",
    headers = [
        "Immutables.h",
    ],
    exported_deps = [
        "//folly/settings:immutables",
    ],
)
