load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_rust_library.bzl", "fb_dirsync_rust_library")

oncall("rust_libraries")

fb_dirsync_rust_library(
    name = "folly_dynamic",
    srcs = ["dynamic.rs"],
    cpp_deps = [":dynamic-ffi"],
    crate_root = "dynamic.rs",
    cxx_bridge = "dynamic.rs",
    deps = [
        "fbsource//third-party/rust:cxx",
        "fbsource//xplat/folly/rust/string:string",
    ],
)

fb_dirsync_cpp_library(
    name = "dynamic-ffi",
    srcs = ["dynamic.cpp"],
    headers = ["dynamic.h"],
    preferred_linkage = "static",
    exported_deps = [
        "fbsource//third-party/rust:cxx-core",
        "//folly/json:dynamic",
    ],
)
