load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load("../defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "iobuf",
    srcs = [
        "Cursor.cpp",
        "IOBuf.cpp",
        "IOBufIovecBuilder.cpp",
        "IOBufQueue.cpp",
    ],
    headers = [
        "Cursor.h",
        "Cursor-inl.h",
        "IOBuf.h",
        "IOBufIovecBuilder.h",
        "IOBufQueue.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:conv",
        "//folly/hash:spooky_hash_v2",
        "//folly/lang:align",
        "//folly/lang:hint",
        "//folly/memory:sanitize_address",
        "//folly/portability:iovec",
    ],
    exported_deps = [
        "//folly:fbstring",
        "//folly:fbvector",
        "//folly:function",
        "//folly:likely",
        "//folly:memory",
        "//folly:portability",
        "//folly:range",
        "//folly:scope_guard",
        "//folly/container:span",
        "//folly/detail:iterators",
        "//folly/lang:bits",
        "//folly/lang:checked_math",
        "//folly/lang:exception",
        "//folly/lang:ordering",
        "//folly/memory:malloc",
        "//folly/memory:memory_resource",
        "//folly/portability:sys_uio",
        "//folly/synchronization:micro_spin_lock",
    ],
    external_deps = ["glog"],
    exported_external_deps = [
        "glog",
    ],
)

fb_dirsync_cpp_library(
    name = "global_shutdown_socket_set",
    srcs = ["GlobalShutdownSocketSet.cpp"],
    headers = ["GlobalShutdownSocketSet.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:singleton",
    ],
    exported_deps = [
        ":shutdown_socket_set",
        "//folly/concurrency/memory:read_mostly_shared_ptr",
    ],
)

fb_dirsync_cpp_library(
    name = "record_io",
    srcs = [
        "RecordIO.cpp",
    ],
    headers = [
        "RecordIO.h",
        "RecordIO-inl.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    supports_python_dlopen = True,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:exception",
        "//folly:file_util",
        "//folly:memory",
        "//folly:string",
        "//folly/portability:unistd",
    ],
    exported_deps = [
        ":iobuf",
        "//folly:file",
        "//folly:range",
        "//folly/detail:iterators",
        "//folly/hash:spooky_hash_v2",
        "//folly/system:memory_mapping",
    ],
)

fb_dirsync_cpp_library(
    name = "shutdown_socket_set",
    srcs = ["ShutdownSocketSet.cpp"],
    headers = ["ShutdownSocketSet.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:file_util",
        "//folly/net:net_ops",
        "//folly/portability:sockets",
    ],
    exported_deps = [
        "//folly:file",
        "//folly/net:network_socket",
        "//folly/synchronization:relaxed_atomic",
    ],
    external_deps = [
        "glog",
    ],
)

fb_dirsync_cpp_library(
    name = "typed_io_buf",
    headers = ["TypedIOBuf.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":iobuf",
        "//folly/memory:malloc",
    ],
)

fb_dirsync_cpp_library(
    name = "socket_option_map",
    srcs = [
        "SocketOptionMap.cpp",
        "SocketOptionValue.cpp",
    ],
    headers = [
        "SocketOptionMap.h",
        "SocketOptionValue.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/net:network_socket",
        "//folly/portability:sockets",
    ],
)

fb_dirsync_cpp_library(
    name = "huge_pages",
    srcs = ["HugePages.cpp"],
    headers = ["HugePages.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:conv",
        "//folly:format",
        "//folly:string",
        "//folly/gen:base",
        "//folly/gen:file",
        "//folly/gen:string",
        "//folly/portability:windows",
    ],
    exported_deps = [
        "//folly:range",
        "//folly/experimental/io:fs_util",
        "//folly/portability:unistd",
    ],
    external_deps = [
        ("boost", None, "boost_regex"),
        "boost",
    ],
    exported_external_deps = [
        "boost",
    ],
)

fb_dirsync_cpp_library(
    name = "fs_util",
    srcs = ["FsUtil.cpp"],
    headers = ["FsUtil.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:exception",
        "//folly/portability:windows",
    ],
    external_deps = [("boost", None, "boost_filesystem")],
    exported_external_deps = [
        ("boost", None, "boost_filesystem"),
    ],
)
