load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "async_test",
    srcs = ["AsyncTest.cpp"],
    headers = [],
    deps = [
        "//folly/coro:blocking_wait",
        "//folly/coro:sleep",
        "//folly/fibers:core_manager",
        "//folly/fibers:fiber_manager_map",
        "//folly/fibers/async:baton",
        "//folly/fibers/async:collect",
        "//folly/fibers/async:core",
        "//folly/fibers/async:fiber_manager",
        "//folly/fibers/async:future",
        "//folly/fibers/async:promise",
        "//folly/fibers/async:stack_tracing",
        "//folly/fibers/async:task",
        "//folly/fibers/async:wait_utils",
        "//folly/io/async:async_base",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
