load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load(
    "../defs.bzl",
    "folly_xplat_library",
)

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "observable",
    headers = [
        "Observable.h",
        "Observable-inl.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":observer",
        "//folly:function",
        "//folly/synchronization:baton",
    ],
)

fb_dirsync_cpp_library(
    name = "with_jitter",
    headers = [
        "WithJitter.h",
        "WithJitter-inl.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/glog:glog",
        "//folly:default_keep_alive_executor",
        "//folly:random",
        "//folly:synchronized",
        "//folly/executors:global_executor",
        "//folly/futures:core",
        "//folly/observer:observable",
        "//folly/observer:observer",
    ],
)

fb_dirsync_cpp_library(
    name = "observer",
    headers = [
        "Observer.h",
        "Observer-inl.h",
        "Observer-pre.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:shared_mutex",
        "//folly:synchronized",
        "//folly:thread_local",
        "//folly/experimental/observer/detail:observer_manager",
        "//folly/functional:invoke",
    ],
)

fb_dirsync_cpp_library(
    name = "simple_observable",
    headers = [
        "SimpleObservable.h",
        "SimpleObservable-inl.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:function",
        "//folly:synchronized",
        "//folly/observer:observable",
        "//folly/observer:observer",
        "//folly/synchronization:delayed_init",
    ],
)

# !!!! fbcode/folly/observer/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "hazptr_observer",
    headers = [
        "HazptrObserver.h",
    ],
    exported_deps = [
        "//folly:synchronized",
        "//folly/experimental/observer/detail:observer_manager",
        "//folly/observer:observer",
        "//folly/synchronization:hazptr",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "read_mostly_tl_observer",
    headers = [
        "ReadMostlyTLObserver.h",
    ],
    exported_deps = [
        "//folly/concurrency/memory:read_mostly_shared_ptr",
        "//folly/experimental/observer/detail:observer_manager",
        "//folly/observer:observer",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "core_cached_observer",
    headers = [
        "CoreCachedObserver.h",
    ],
    exported_deps = [
        "//folly/concurrency:core_cached_shared_ptr",
        "//folly/experimental/observer/detail:observer_manager",
        "//folly/observer:observer",
    ],
)
