load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "i_o_buf_demo",
    srcs = ["IOBuf.cpp"],
    headers = [],
    deps = [
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)
