load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "openssl",
    exported_deps = [
        "//folly/io/async/ssl:openssl_utils",  # @manual
        "//folly/io/async/ssl:ssl_errors",  # @manual
    ],
)

fb_dirsync_cpp_library(
    name = "basic_transport_certificate",
    headers = ["BasicTransportCertificate.h"],
    use_raw_headers = True,
    exported_deps = [
        ":openssl_transport_certificate",
    ],
)

fb_dirsync_cpp_library(
    name = "openssl_transport_certificate",
    headers = ["OpenSSLTransportCertificate.h"],
    use_raw_headers = True,
    exported_deps = [
        "//folly/io/async:async_transport_certificate",
        "//folly/portability:openssl",
        "//folly/ssl:openssl_ptr_types",
    ],
)

fb_dirsync_cpp_library(
    name = "openssl_utils",
    srcs = ["OpenSSLUtils.cpp"],
    headers = ["OpenSSLUtils.h"],
    use_raw_headers = True,
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:scope_guard",
        "//folly/portability:unistd",
        "//folly/ssl/detail:openssl_session",
    ],
    exported_deps = [
        "//folly:range",
        "//folly/io/async:async_socket_exception",
        "//folly/net:network_socket",
        "//folly/portability:openssl",
        "//folly/portability:sockets",
        "//folly/ssl:openssl_ptr_types",
        "//folly/ssl:ssl_session",
    ],
)

fb_dirsync_cpp_library(
    name = "ssl_errors",
    srcs = ["SSLErrors.cpp"],
    headers = ["SSLErrors.h"],
    use_raw_headers = True,
    deps = [
        "//folly:range",
        "//folly/portability:openssl",
    ],
    exported_deps = [
        "//folly/io/async:async_socket_exception",
    ],
)

fb_dirsync_cpp_library(
    name = "tls_definitions",
    headers = ["TLSDefinitions.h"],
    use_raw_headers = True,
    exported_deps = [
        "//folly/io:iobuf",
    ],
)
