load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("../../../defs.bzl", "folly_xplat_cxx_library")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "openssl",
)

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "basic_transport_certificate",
    raw_headers = ["BasicTransportCertificate.h"],
    exported_deps = [
        "//xplat/folly/io/async:async_transport_certificate",
        "//xplat/folly/io/async/ssl:openssl_transport_certificate",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "openssl_transport_certificate",
    raw_headers = ["OpenSSLTransportCertificate.h"],
    deps = ["//xplat/folly/io/async:async_transport_certificate"],
    exported_deps = [
        "fbsource//xplat/folly/portability:openssl",
        "//xplat/folly/ssl:openssl_ptr_types",
    ],
)

fb_dirsync_cpp_library(
    name = "openssl_utils",
    srcs = ["OpenSSLUtils.cpp"],
    headers = ["OpenSSLUtils.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:scope_guard",
        "//folly/portability:unistd",
        "//folly/ssl/detail:openssl_session",
    ],
    exported_deps = [
        "//folly:range",
        "//folly/io/async:async_socket_exception",
        "//folly/net:network_socket",
        "//folly/portability:openssl",
        "//folly/portability:sockets",
        "//folly/ssl:openssl_ptr_types",
        "//folly/ssl:ssl_session",
    ],
)

fb_dirsync_cpp_library(
    name = "ssl_errors",
    srcs = ["SSLErrors.cpp"],
    headers = ["SSLErrors.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    deps = [
        "//folly:range",
        "//folly/portability:openssl",
    ],
    exported_deps = [
        "//folly/io/async:async_socket_exception",
    ],
)

fb_dirsync_cpp_library(
    name = "tls_definitions",
    headers = ["TLSDefinitions.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    exported_deps = [
        "//folly/io:iobuf",
    ],
)

# !!!! fbcode/folly/io/async/ssl/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "openssl",
    exported_deps = [
        "//folly/io/async/ssl:openssl_utils",  # @manual
        "//folly/io/async/ssl:ssl_errors",  # @manual
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "basic_transport_certificate",
    headers = ["BasicTransportCertificate.h"],
    exported_deps = [
        ":openssl_transport_certificate",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "openssl_transport_certificate",
    headers = ["OpenSSLTransportCertificate.h"],
    exported_deps = [
        "//folly/io/async:async_transport_certificate",
        "//folly/portability:openssl",
        "//folly/ssl:openssl_ptr_types",
    ],
)
