load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "hazptr_lock_free_lifo",
    headers = ["HazptrLockFreeLIFO.h"],
    exported_deps = [
        "//folly/synchronization:hazptr",
    ],
)

cpp_library(
    name = "hazptr_swmr_set",
    headers = ["HazptrSWMRSet.h"],
    exported_deps = [
        "//folly/synchronization:hazptr",
    ],
)

cpp_library(
    name = "hazptr_wide_cas",
    headers = ["HazptrWideCAS.h"],
    exported_deps = [
        "//folly/synchronization:hazptr",
    ],
)
