load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "hash_demo",
    srcs = ["Hash.cpp"],
    headers = [],
    deps = [
        "//folly/hash:hash",
        "//folly/portability:gtest",
    ],
)
