load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "hash_demo",
    srcs = ["Hash.cpp"],
    headers = [],
    deps = [
        "//folly/hash:hash",
        "//folly/portability:gtest",
    ],
)
