load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("../defs.bzl", "folly_xplat_cxx_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "hex",
    headers = ["hex.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    exported_deps = [
        "//folly/lang:align",
        "//folly/lang:assume",
    ],
)

fb_dirsync_cpp_library(
    name = "uuid",
    headers = ["Uuid.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    exported_deps = [
        "//folly:portability",
        "//folly/memory:uninitialized_memory_hacks",
    ],
)
