load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_cxx_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "hex",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["hex.h"],
    exported_deps = [
        "//xplat/folly/lang:align",
        "//xplat/folly/lang:assume",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "uuid",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["Uuid.h"],
    exported_deps = [
        "//xplat/folly:cpu_id",
        "//xplat/folly:expected",
        "//xplat/folly:portability",
        "//xplat/folly:unit",
        "//xplat/folly/memory:uninitialized_memory_hacks",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "hex",
    headers = ["hex.h"],
    exported_deps = [
        "//folly/lang:align",
        "//folly/lang:assume",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "uuid",
    headers = ["Uuid.h"],
    exported_deps = [
        "//folly:portability",
        "//folly/memory:uninitialized_memory_hacks",
    ],
)
