load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "testbser",
    srcs = ["BserTest.cpp"],
    headers = [],
    deps = [
        "//folly:string",
        "//folly/json/bser:bser",
        "//folly/portability:gtest",
    ],
)
