load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "testbser",
    srcs = ["BserTest.cpp"],
    headers = [],
    deps = [
        "//folly:string",
        "//folly/experimental/bser:bser",
        "//folly/portability:gtest",
    ],
)
