load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_binary.bzl", "fb_dirsync_cpp_binary")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_binary(
    name = "fatal_helper",
    srcs = ["FatalHelper.cpp"],
    deps = [
        "//folly/init:init",
        "//folly/logging:logging",
        "//folly/portability:stdlib",
    ],
)

fb_dirsync_cpp_binary(
    name = "log_after_main",
    srcs = ["LogAfterMain.cpp"],
    deps = [
        ":helpers",
        ":log_on_shutdown",
        "//folly/init:init",
        "//folly/logging:logging",
    ],
)

fb_dirsync_cpp_binary(
    name = "log_after_main_no_init",
    srcs = ["LogAfterMainNoInit.cpp"],
    deps = [
        ":helpers",
    ],
)

fb_dirsync_cpp_library(
    name = "helpers",
    headers = ["helpers.h"],
    exported_deps = [
        "//folly/logging:logging",
    ],
)

fb_dirsync_cpp_library(
    name = "log_on_shutdown",
    srcs = ["LogOnShutdownLib.cpp"],
    headers = ["LogOnShutdownLib.h"],
    deps = [
        ":helpers",
    ],
)
