load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "bind_test",
    srcs = ["BindTest.cpp"],
    deps = [
        "//folly/lang/bind:bind",
        "//folly/portability:gtest",
    ],
)

fbcode_target(
    _kind = cpp_unittest,
    name = "named_test",
    srcs = ["NamedTest.cpp"],
    deps = [
        "//folly/lang/bind:named",
        "//folly/portability:gtest",
    ],
)

fbcode_target(
    _kind = cpp_unittest,
    name = "named_to_storage_test",
    srcs = ["NamedToStorageTest.cpp"],
    deps = [
        "//folly/lang/bind:named_to_storage",
        "//folly/portability:gtest",
    ],
)

fbcode_target(
    _kind = cpp_unittest,
    name = "to_storage_test",
    srcs = ["ToStorageTest.cpp"],
    deps = [
        "//folly/lang/bind:to_storage",
        "//folly/portability:gtest",
    ],
)
