load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("fbcode_entropy_wardens_folly")

python_unittest(
    name = "test_float_format_python_json",
    srcs = ["test_float_format_python_json.py"],
    deps = [
        "fbcode//folly/json/test:folly_json_serialize",
    ],
)
