load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "test_main",
    deps = [
        ":test_main_lib",
    ],
)

cpp_library(
    name = "test_main_lib",
    srcs = ["TestMain.cpp"],
    deps = [
        "//folly:portability",
        "//folly/init:init",
        "//folly/portability:gflags",
        "//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)
