load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "test_main",
    srcs = ["TestMain.cpp"],
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:portability",
        "//folly/init:init",
        "//folly/portability:gflags",
        "//folly/portability:gtest",
    ],
)
