load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "socket_file_descriptor_map_test",
    srcs = ["SocketFileDescriptorMapTest.cpp"],
    deps = [
        "//folly:portability",
        "//folly/net/detail:socket_file_descriptor_map",
        "//folly/portability:fcntl",
        "//folly/portability:gtest",
        "//folly/portability:sockets",
        "//folly/portability:unistd",
        "//folly/portability:windows",
    ],
)
