FROM mcr.microsoft.com/devcontainers/base:jammy

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        watchman \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
