load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_library")

oncall("fbcode_entropy_wardens_folly")

# xplat build rules

fb_dirsync_cpp_library(
    name = "dwarf",
    headers = [
        "Dwarf.h",
        "DwarfImpl.h",
        "DwarfLineNumberVM.h",
        "DwarfSection.h",
        "DwarfUtil.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/debugging/symbolizer:dwarf",
    ],
)

fb_dirsync_cpp_library(
    name = "elf",
    headers = [
        "Elf.h",
        "Elf-inl.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/debugging/symbolizer:elf",
    ],
)

fb_dirsync_cpp_library(
    name = "elf_cache",
    headers = [
        "ElfCache.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/debugging/symbolizer:elf_cache",
    ],
)

fb_dirsync_cpp_library(
    name = "line_reader",
    headers = [
        "LineReader.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/debugging/symbolizer:line_reader",
    ],
)

fb_dirsync_cpp_library(
    name = "stack_trace",
    headers = [
        "StackTrace.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/debugging/symbolizer:stack_trace",
    ],
)

fb_dirsync_cpp_library(
    name = "symbolized_frame",
    headers = [
        "SymbolizedFrame.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/debugging/symbolizer:symbolized_frame",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "symbolizer",
    raw_headers = [
        "SignalHandler.h",
        "SymbolizePrinter.h",
        "Symbolizer.h",
    ],
    exported_deps = ["//xplat/folly/debugging/symbolizer:symbolizer"],
)

# fbcode build rules

fbcode_target(
    _kind = cpp_library,
    name = "symbolize_printer",
    headers = [
        "SymbolizePrinter.h",
    ],
    exported_deps = [
        "//folly/debugging/symbolizer:symbolize_printer",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "symbolizer",
    headers = [
        "Symbolizer.h",
    ],
    exported_deps = [
        "//folly/debugging/symbolizer:symbolizer",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "signal_handler",
    headers = [
        "SignalHandler.h",
    ],
    exported_deps = [
        "//folly/debugging/symbolizer:signal_handler",
    ],
)
