load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_rule.bzl", "fb_dirsync_rule")
load("../../defs.bzl", "folly_xplat_cxx_test")
load("../../io/async/test/certs/defs.bzl", "alias_pem", "alias_pem_for_xplat")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "openssl_hash_test",
    srcs = ["OpenSSLHashTest.cpp"],
    deps = [
        "//folly/io:iobuf",
        "//folly/portability:gtest",
        "//folly/ssl:openssl_hash",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_cxx_test,
    name = "openssl_cert_utils_test",
    srcs = ["OpenSSLCertUtilsTest.cpp"],
    resources = {
        # this dict is neccessary for correct mapping.
        # :ca-cert.pem is at folly/ssl/test/certs/ca-cert.pem
        # The test expect to find the resource at folly/ssl/test/ca-cert.pem
        "ca-cert.pem": ":ca-cert.pem",
        "tests-cert.pem": ":tests-cert.pem",
    },
    deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//xplat/folly/portability:gmock",
        "fbsource//xplat/folly/portability:gtest",
        "fbsource//xplat/folly/portability:openssl",
        "fbsource//xplat/folly/portability:time",
        "//xplat/folly:format",
        "//xplat/folly:range",
        "//xplat/folly:string",
        "//xplat/folly/container:enumerate",
        "//xplat/folly/ssl:openssl_cert_utils",
        "//xplat/folly/ssl:openssl_ptr_types",
        "//xplat/folly/testing:test_util",
    ],
)

fb_dirsync_cpp_unittest(
    name = "ssl_session_manager_test",
    srcs = ["SSLSessionManagerTest.cpp"],
    deps = [
        "//folly/portability:gtest",
        "//folly/portability:openssl",
        "//folly/ssl:openssl_ptr_types",
        "//folly/ssl:ssl_session_manager",
        "//folly/ssl/detail:openssl_session",
    ],
)

fb_dirsync_cpp_unittest(
    name = "openssl_key_utils_test",
    srcs = ["OpenSSLKeyUtilsTest.cpp"],
    deps = [
        "//folly/portability:gtest",
        "//folly/ssl:openssl_key_utils",
        "//folly/ssl:password_collector",
    ],
)

# !!!! fbcode/folly/ssl/test/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fb_dirsync_rule(
    name = "pem_aliases",
    fbcode_rule = alias_pem,
    pems = [
        "tests-cert.pem",
        "ca-cert.pem",
    ],
    xplat_rule = alias_pem_for_xplat,
)

fbcode_target(
    _kind = cpp_unittest,
    name = "openssl_cert_utils_test",
    srcs = ["OpenSSLCertUtilsTest.cpp"],
    resources = [
        ":ca-cert.pem",
        ":tests-cert.pem",
    ],
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:format",
        "//folly:range",
        "//folly:string",
        "//folly/container:enumerate",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//folly/portability:openssl",
        "//folly/portability:time",
        "//folly/ssl:openssl_cert_utils",
        "//folly/ssl:openssl_ptr_types",
        "//folly/testing:test_util",
    ],
)
