load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "atomic_queue",
    headers = [
        "AtomicQueue.h",
    ],
    exported_deps = [
        "//folly/channels/detail:atomic_queue",
    ],
)

cpp_library(
    name = "channel_bridge",
    headers = [
        "ChannelBridge.h",
    ],
    exported_deps = [
        "//folly/channels/detail:channel_bridge",
    ],
)

cpp_library(
    name = "function_traits",
    headers = [
        "FunctionTraits.h",
    ],
    exported_deps = [
        "//folly/channels/detail:function_traits",
    ],
)

cpp_library(
    name = "intrusive_ptr",
    headers = [
        "IntrusivePtr.h",
    ],
    exported_deps = [
        "//folly/channels/detail:intrusive_ptr",
    ],
)

cpp_library(
    name = "multiplexer_traits",
    headers = [
        "MultiplexerTraits.h",
    ],
    exported_deps = [
        "//folly/channels/detail:multiplexer_traits",
    ],
)

cpp_library(
    name = "pointer_variant",
    headers = [
        "PointerVariant.h",
    ],
    exported_deps = [
        "//folly/channels/detail:pointer_variant",
    ],
)

cpp_library(
    name = "utility",
    headers = [
        "Utility.h",
    ],
    exported_deps = [
        "//folly/channels/detail:utility",
    ],
)
