load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("../../../defs.bzl", "folly_xplat_cxx_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "atomic_queue",
    headers = [
        "AtomicQueue.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    exported_deps = [
        "//folly/channels/detail:atomic_queue",
    ],
)

fb_dirsync_cpp_library(
    name = "channel_bridge",
    headers = [
        "ChannelBridge.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_cxx_library,
    exported_deps = [
        "//folly/channels/detail:channel_bridge",
    ],
)

# !!!! fbcode/folly/experimental/channels/detail/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "intrusive_ptr",
    headers = [
        "IntrusivePtr.h",
    ],
    exported_deps = [
        "//folly/channels/detail:intrusive_ptr",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "multiplexer_traits",
    headers = [
        "MultiplexerTraits.h",
    ],
    exported_deps = [
        "//folly/channels/detail:multiplexer_traits",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "pointer_variant",
    headers = [
        "PointerVariant.h",
    ],
    exported_deps = [
        "//folly/channels/detail:pointer_variant",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "utility",
    headers = [
        "Utility.h",
    ],
    exported_deps = [
        "//folly/channels/detail:utility",
    ],
)
