load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "now_task_test",
    srcs = ["NowTaskTest.cpp"],
    deps = [
        "//folly/coro:blocking_wait",
        "//folly/coro:gtest_helpers",
        "//folly/coro/safe:now_task",
    ],
)
