load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "captures_test",
    srcs = ["CapturesTest.cpp"],
    deps = [
        "//folly/coro/safe:captures",
        "//folly/lang/bind:bind",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "async_closure_test",
    srcs = ["AsyncClosureTest.cpp"],
    deps = [
        "//folly/coro:gtest_helpers",
        "//folly/coro:timeout",
        "//folly/coro:value_or_fatal",
        "//folly/coro/safe:async_closure",
        "//folly/fibers:semaphore",
        "//folly/init:init",
    ],
)

fb_dirsync_cpp_unittest(
    name = "now_task_test",
    srcs = ["NowTaskTest.cpp"],
    deps = [
        "//folly/coro:async_generator",
        "//folly/coro:blocking_wait",
        "//folly/coro:gtest_helpers",
        "//folly/coro/safe:now_task",
    ],
)

fb_dirsync_cpp_unittest(
    name = "safe_task_test",
    srcs = ["SafeTaskTest.cpp"],
    deps = [
        "//folly/coro:gtest_helpers",
        "//folly/coro:timeout",
        "//folly/coro/safe:safe_task",
        "//folly/fibers:semaphore",
        "//folly/init:init",
        "//folly/portability:gtest",
    ],
)
