load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "test_util",
    srcs = ["TestUtil.cpp"],
    headers = ["TestUtil.h"],
    fbandroid_deps = [
        "//xplat/third-party/linker_lib:atomic",
    ],
    use_raw_headers = True,
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:exception",
        "//folly:file",
        "//folly:file_util",
        "//folly:memory",
        "//folly:string",
        "//folly/ext:test_ext",
        "//folly/ext/buck2:test_ext",
        "//folly/portability:fcntl",
    ],
    exported_deps = [
        "//folly:range",
        "//folly:scope_guard",
        "//folly/io:fs_util",
    ],
    external_deps = [
        ("boost", None, "boost_regex"),
    ],
)
