load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "mock_net_ops_dispatcher",
    headers = [
        "MockNetOpsDispatcher.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/net:net_ops_dispatcher",
        "//folly/portability:gmock",
    ],
)

fb_dirsync_cpp_library(
    name = "mock_tcpinfo_dispatcher",
    headers = [
        "MockTcpInfoDispatcher.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/net:tcpinfo_dispatcher",
        "//folly/portability:gmock",
    ],
)

fb_dirsync_cpp_library(
    name = "net_ops_test",
    srcs = ["NetOpsTest.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly/net:net_ops",
        "//folly/net:network_socket",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "tcpinfo_test",
    srcs = ["TcpInfoTest.cpp"],
    supports_static_listing = False,
    deps = [
        ":tcpinfo_test_util",
        "//folly/net:tcpinfo",
        "//folly/net/test:mock_net_ops_dispatcher",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_library(
    name = "tcpinfo_test_util",
    headers = [
        "TcpInfoTestUtil.h",
    ],
    exported_deps = [
        "//folly/net:tcpinfo",
        "//folly/net/test:mock_net_ops_dispatcher",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)
