load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "binary_heap_test",
    srcs = ["BinaryHeapTest.cpp"],
    headers = [],
    deps = [
        "//folly/algorithm:binary_heap",
        "//folly/portability:gtest",
    ],
)
