load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_benchmark.bzl", "fb_dirsync_cpp_benchmark")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "binary_heap_test",
    srcs = ["BinaryHeapTest.cpp"],
    headers = [],
    deps = [
        "//folly/algorithm:binary_heap",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "stable_radix_sort_test",
    srcs = ["StableRadixSortTest.cpp"],
    headers = [],
    deps = [
        "//folly/algorithm:stable_radix_sort",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "stable_radix_sort_benchmark",
    srcs = ["StableRadixSortBenchmark.cpp"],
    headers = [],
    deps = [
        "//folly:benchmark",
        "//folly/algorithm:stable_radix_sort",
        "//folly/init:init",
        "//folly/stats/detail:double_radix_sort",
    ],
    external_deps = [
        ("boost", None, "boost_sort"),
    ],
)
