load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "clock_test",
    srcs = ["ClockTest.cpp"],
    headers = [],
    deps = [
        "//folly/chrono:clock",
        "//folly/portability:gtest",
    ],
)

fbcode_target(
    _kind = cpp_unittest,
    name = "conv_test",
    srcs = ["ConvTest.cpp"],
    headers = [],
    deps = [
        "//folly/chrono:conv",
        "//folly/portability:gtest",
    ],
    external_deps = [
        "glog",
    ],
)
