load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_benchmark.bzl", "cpp_benchmark")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "reproducible_accumulator_test",
    srcs = ["ReproducibleAccumulatorTest.cpp"],
    headers = [],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:benchmark_util",
        "//folly/math:reproducible_accumulator",
        "//folly/portability:gtest",
    ],
)

fbcode_target(
    _kind = cpp_benchmark,
    name = "reproducible_accumulator_benchmark",
    srcs = ["ReproducibleAccumulatorBenchmark.cpp"],
    headers = [],
    deps = [
        "//folly:benchmark",
        "//folly/init:init",
        "//folly/math:reproducible_accumulator",
    ],
)
