load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "test_util_test",
    srcs = ["TestUtilTest.cpp"],
    headers = [],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:memory",
        "//folly/portability:fcntl",
        "//folly/portability:gtest",
        "//folly/portability:stdlib",
        "//folly/portability:unistd",
        "//folly/testing:test_util",
    ],
    external_deps = [
        ("boost", None, "boost_algorithm"),
    ],
)
