load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "transport_test",
    srcs = [
        "TransportTest.cpp",
    ],
    deps = [
        "//folly:portability",
        "//folly/coro:blocking_wait",
        "//folly/coro:collect",
        "//folly/io/async/test:async_socket_test_lib",
        "//folly/io/async/test:mocks",
        "//folly/io/async/test:scoped_bound_port",
        "//folly/io/coro:socket",
        "//folly/portability:gtest",
    ],
)
