load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "bucket",
    headers = ["Bucket.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:constexpr_math",
    ],
)

fb_dirsync_cpp_library(
    name = "buffered_stat",
    srcs = [],
    headers = [
        "BufferedStat.h",
        "BufferedStat-inl.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":sliding_window",
        "//folly:range",
        "//folly:shared_mutex",
        "//folly/stats:digest_builder",
    ],
)

fb_dirsync_cpp_library(
    name = "double_radix_sort",
    srcs = [
        "DoubleRadixSort.cpp",
    ],
    headers = [
        "DoubleRadixSort.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    external_deps = [
        "glog",
    ],
)

fb_dirsync_cpp_library(
    name = "sliding_window",
    srcs = [
    ],
    headers = [
        "SlidingWindow.h",
        "SlidingWindow-inl.h",
    ],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:function",
    ],
)
