load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load(
    "@fbsource//tools/build_defs:platform_defs.bzl",
    "ANDROID",
    "APPLE",
    "CXX",
    "WINDOWS",
)
load(
    "../../defs.bzl",
    "FBANDROID_CXXFLAGS",
    "FBOBJC_CXXFLAGS",
    "folly_xplat_cxx_test",
)

oncall("fbcode_entropy_wardens_folly")

# xplat build rules

non_fbcode_target(
    _kind = folly_xplat_cxx_test,
    name = "hash_test",
    srcs = ["hash_test.cpp"],
    fbandroid_compiler_flags = FBANDROID_CXXFLAGS,
    fbobjc_compiler_flags = FBOBJC_CXXFLAGS,
    platforms = (ANDROID, APPLE, CXX, WINDOWS),
    deps = [
        "//xplat/folly/container:span",
        "//xplat/folly/portability:gtest",
        "//xplat/folly/random:hash",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_cxx_test,
    name = "xoshiro256pp_test",
    srcs = ["Xoshiro256ppTest.cpp"],
    fbandroid_compiler_flags = FBANDROID_CXXFLAGS,
    fbobjc_compiler_flags = FBOBJC_CXXFLAGS,
    platforms = (ANDROID, APPLE, CXX, WINDOWS),
    deps = [
        "//xplat/folly/lang:keep",
        "//xplat/folly/portability:gtest",
        "//xplat/folly/random:xoshiro256pp",
    ],
)

# fbcode build rules

fbcode_target(
    _kind = cpp_unittest,
    name = "hash_test",
    srcs = ["hash_test.cpp"],
    deps = [
        "//folly/container:span",
        "//folly/portability:gtest",
        "//folly/random:hash",
    ],
)

fbcode_target(
    _kind = cpp_unittest,
    name = "xoshiro256pp_test",
    srcs = ["Xoshiro256ppTest.cpp"],
    deps = [
        "//folly/lang:keep",
        "//folly/portability:gtest",
        "//folly/random:xoshiro256pp",
    ],
)
