load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load("../../defs.bzl", "folly_xplat_cxx_library")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "bindings",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["Bindings.h"],
    exported_deps = [
        "//xplat/folly:traits",
        "//xplat/folly/lang:bindings",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "bindings",
    headers = ["Bindings.h"],
    exported_deps = [
        "//folly:traits",
        "//folly/lang:bindings",
    ],
)
