load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "f14_detail_test",
    srcs = [
        "F14DetailTest.cpp",
    ],
    deps = [
        "//folly/container/detail:f14_hash_detail",
        "//folly/portability:gtest",
    ],
)
