load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_binary.bzl", "fb_dirsync_cpp_binary")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_binary(
    name = "json_schema_tester",
    srcs = ["JSONSchemaTester.cpp"],
    headers = [],
    deps = [
        "//folly/json:dynamic",
        "//folly/json:json_schema",
    ],
)
