load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_benchmark.bzl", "fb_dirsync_cpp_benchmark")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "checksum_test",
    srcs = ["ChecksumTest.cpp"],
    deps = [
        "//folly:benchmark",
        "//folly:portability",
        "//folly:random",
        "//folly/external/fast-crc32:avx512_crc32c_v8s3x4",
        "//folly/external/fast-crc32:neon_crc32c_v3s4x2e_v2",
        "//folly/external/fast-crc32:neon_eor3_crc32c_v8s2x4e_s2x1",
        "//folly/external/fast-crc32:sse_crc32c_v8s3x3",
        "//folly/hash:checksum",
        "//folly/hash:hash",
        "//folly/hash/detail:checksum_detail",
        "//folly/portability:gflags",
        "//folly/portability:gtest",
    ],
    external_deps = [
        "boost",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "checksum_benchmark",
    srcs = ["ChecksumBenchmark.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:benchmark",
        "//folly:memory",
        "//folly/hash:checksum",
    ],
)

fb_dirsync_cpp_unittest(
    name = "farm_hash_test",
    srcs = ["FarmHashTest.cpp"],
    headers = [],
    deps = [
        "//folly/hash:farm_hash",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "hash_benchmark",
    srcs = ["HashBenchmark.cpp"],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/glog:glog",
        "//folly:benchmark",
        "//folly:preprocessor",
        "//folly/hash:hash",
        "//folly/hash:murmur_hash",
        "//folly/hash:rapidhash",
        "//folly/lang:keep",
        "//folly/portability:gflags",
    ],
)

fb_dirsync_cpp_unittest(
    name = "hash_test",
    srcs = ["HashTest.cpp"],
    supports_static_listing = False,
    deps = [
        "//folly:conv",
        "//folly:map_util",
        "//folly:random",
        "//folly:range",
        "//folly/hash:hash",
        "//folly/lang:cstring_view",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "rapidhash_test",
    srcs = ["RapidHashTest.cpp"],
    deps = [
        "//folly/hash:rapidhash",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "spooky_hash_v1_test",
    srcs = ["SpookyHashV1Test.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly/hash:spooky_hash_v1",
        "//folly/portability:gtest",
        "//folly/portability:time",
    ],
)

fb_dirsync_cpp_unittest(
    name = "spooky_hash_v2_test",
    srcs = ["SpookyHashV2Test.cpp"],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly/hash:spooky_hash_v2",
        "//folly/portability:gtest",
        "//folly/portability:time",
    ],
)

fb_dirsync_cpp_unittest(
    name = "traits_test",
    srcs = ["traits_test.cpp"],
    deps = [
        "//folly/hash:traits",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "murmur_hash_test",
    srcs = ["MurmurHashTest.cpp"],
    deps = [
        "//folly/hash:murmur_hash",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "std_compatible_hash_test",
    srcs = ["StdCompatibleHashTest.cpp"],
    deps = [
        "//folly/hash:hash",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "unique_hash_key_test",
    srcs = ["UniqueHashKeyTest.cpp"],
    supports_static_listing = False,
    deps = [
        "//folly/container:f14_hash",
        "//folly/container:map_util",
        "//folly/hash:unique_hash_key",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "fnv_hash_test",
    srcs = ["FnvHashTest.cpp"],
    deps = [
        "//folly/hash:fnv_hash",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "hsieh_hash_test",
    srcs = ["HsiehHashTest.cpp"],
    deps = [
        "//folly/hash:hsieh_hash",
        "//folly/portability:gtest",
    ],
)
