load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fbcode_entropy_wardens_folly")

cpp_binary(
    name = "jsonfuzztest.so",
    srcs = ["JsonFuzzTest.cpp"],
    headers = [],
    dlopen_enabled = True,
    deps = [
        "//common/testing/fuzztest:fuzz_main",  # @manual
        "//common/testing/fuzztest:headers",
        "//folly/json:dynamic",
        "//folly/portability:gtest",
    ],
)
