load("@fbcode_macros//build_defs:cpp_benchmark.bzl", "cpp_benchmark")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "momemask_test",
    srcs = ["MovemaskTest.cpp"],
    headers = [],
    deps = [
        "//folly:portability",
        "//folly/algorithm/simd:movemask",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "find_fixed_test",
    srcs = ["FindFixedTest.cpp"],
    headers = [],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:portability",
        "//folly/algorithm/simd:find_fixed",
        "//folly/portability:gtest",
    ],
)

cpp_benchmark(
    name = "find_fixed_bench",
    srcs = ["FindFixedBenchmark.cpp"],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:benchmark",
        "//folly/algorithm/simd:find_fixed",
        "//folly/init:init",
    ],
)
