load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "flat_combining",
    headers = ["FlatCombining.h"],
    exported_deps = [
        "//folly:function",
        "//folly:indexed_mem_pool",
        "//folly:portability",
        "//folly/concurrency:cache_locality",
        "//folly/synchronization:saturating_semaphore",
        "//folly/system:thread_name",
    ],
)
