load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load(
    "@fbsource//xplat/folly:defs.bzl",
    "folly_xplat_library",
)
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "flat_combining",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = [
        "FlatCombining.h",
    ],
    deps = [
        "//xplat/folly:synchronization_flat_combining",
    ],
)

# !!!! fbcode/folly/experimental/flat_combining/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "flat_combining",
    headers = [
        "FlatCombining.h",
    ],
    exported_deps = [
        "//folly/synchronization:flat_combining",
    ],
)
