load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "flat_combining",
    headers = [
        "FlatCombining.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/synchronization:flat_combining",
    ],
)
