# This file needs to exist to avoid build system breakage, see https://fburl.com/workplace/jtdlgdmd
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

oncall("fbcode_entropy_wardens_folly")

fb_native.config_setting(
    name = "folly-conv-dtoa-to-chars",
    values = {
        "folly.conv_dtoa_to_chars": "true",
    },
    visibility = ["PUBLIC"],
)
