load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "observable",
    headers = [
        "Observable.h",
        "Observable-inl.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/observer:observable",
    ],
)

fb_dirsync_cpp_library(
    name = "with_jitter",
    headers = [
        "WithJitter.h",
        "WithJitter-inl.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/observer:with_jitter",
    ],
)

fb_dirsync_cpp_library(
    name = "observer",
    headers = [
        "Observer.h",
        "Observer-inl.h",
        "Observer-pre.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/observer:observer",
    ],
)

fb_dirsync_cpp_library(
    name = "simple_observable",
    headers = [
        "SimpleObservable.h",
        "SimpleObservable-inl.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "//folly/observer:simple_observable",
    ],
)

# !!!! fbcode/folly/experimental/observer/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "hazptr_observer",
    headers = [
        "HazptrObserver.h",
    ],
    exported_deps = [
        "//folly/observer:hazptr_observer",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "read_mostly_tl_observer",
    headers = [
        "ReadMostlyTLObserver.h",
    ],
    exported_deps = [
        "//folly/observer:read_mostly_tl_observer",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "core_cached_observer",
    headers = [
        "CoreCachedObserver.h",
    ],
    exported_deps = [
        "//folly/observer:core_cached_observer",
    ],
)
