load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "observable",
    headers = [
        "Observable.h",
        "Observable-inl.h",
    ],
    exported_deps = [
        "//folly/observer:observable",
    ],
)

cpp_library(
    name = "observer",
    headers = [
        "Observer.h",
        "Observer-inl.h",
        "Observer-pre.h",
    ],
    exported_deps = [
        "//folly/observer:observer",
    ],
)

cpp_library(
    name = "hazptr_observer",
    headers = [
        "HazptrObserver.h",
    ],
    exported_deps = [
        "//folly/observer:hazptr_observer",
    ],
)

cpp_library(
    name = "read_mostly_tl_observer",
    headers = [
        "ReadMostlyTLObserver.h",
    ],
    exported_deps = [
        "//folly/observer:read_mostly_tl_observer",
    ],
)

cpp_library(
    name = "core_cached_observer",
    headers = [
        "CoreCachedObserver.h",
    ],
    exported_deps = [
        "//folly/observer:core_cached_observer",
    ],
)

cpp_library(
    name = "simple_observable",
    headers = [
        "SimpleObservable.h",
        "SimpleObservable-inl.h",
    ],
    exported_deps = [
        "//folly/observer:simple_observable",
    ],
)

cpp_library(
    name = "with_jitter",
    headers = [
        "WithJitter.h",
        "WithJitter-inl.h",
    ],
    exported_deps = [
        "//folly/observer:with_jitter",
    ],
)
