load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")
load("@fbsource//tools/target_determinator/macros:ci.bzl", "ci")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "x86_test",
    srcs = ["x86_test.cpp"],
    labels = ci.labels(
        ci.linux(ci.x86_64()),
        ci.mac(ci.x86_64()),
        ci.windows(ci.x86_64()),
        ci.linux(ci.aarch64()),
        ci.mac(ci.aarch64()),
        # ci.windows(ci.aarch64()), # platform does not exist!
    ),
    deps = [
        "//folly/portability:gmock",
        "//folly/portability:gtest",
        "//folly/system/arch:x86",
    ],
)
