load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")
load("../../defs.bzl", "folly_xplat_cxx_library")

oncall("fbcode_entropy_wardens_folly")

### this line is a hint for source control merge

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "bind",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["Bind.h"],
    exported_deps = [
        "//xplat/folly:utility",
        "//xplat/folly/detail:tuple",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "bind",
    headers = ["Bind.h"],
    exported_deps = [
        "//folly:utility",
        "//folly/detail:tuple",
    ],
)

### this line is a hint for source control merge

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "named",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["Named.h"],
    exported_deps = [
        ":bind",
        "//xplat/folly:traits",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "named",
    headers = ["Named.h"],
    exported_deps = [
        ":bind",
        "//folly:traits",
    ],
)

### this line is a hint for source control merge

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "named_to_storage",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["NamedToStorage.h"],
    exported_deps = [
        ":named",
        ":to_storage",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "named_to_storage",
    headers = ["NamedToStorage.h"],
    exported_deps = [
        ":named",
        ":to_storage",
    ],
)

### this line is a hint for source control merge

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "to_storage",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["ToStorage.h"],
    exported_deps = [
        ":bind",
        "//xplat/folly:utility",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "to_storage",
    headers = ["ToStorage.h"],
    exported_deps = [
        ":bind",
        "//folly:utility",
    ],
)

### this line is a hint for source control merge

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "as_argument",
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["AsArgument.h"],
    exported_deps = [
        ":bind",
        "//xplat/folly:utility",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "as_argument",
    headers = ["AsArgument.h"],
    exported_deps = [
        ":bind",
        "//folly:utility",
    ],
)
