load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs:default_platform_defs.bzl", "ANDROID", "APPLE", "CXX", "FBCODE", "WINDOWS")
load("@fbsource//tools/build_defs:fb_xplat_cxx_library.bzl", "fb_xplat_cxx_library")
load("@fbsource//tools/build_defs:glob_defs.bzl", "subdir_glob")
load("../../../defs.bzl", "DEFAULT_APPLE_SDKS")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = fb_xplat_cxx_library,
    name = "test-headers",
    header_namespace = "",
    exported_headers = subdir_glob(
        [
            ("", "**/*.h"),
        ],
        prefix = "folly/experimental/flat_combining/test",
    ),
    apple_sdks = DEFAULT_APPLE_SDKS,
    force_static = True,
    platforms = (ANDROID, APPLE, CXX, FBCODE, WINDOWS),
    visibility = ["PUBLIC"],
)

# !!!! fbcode/folly/experimental/flat_combining/test/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "flat_combining_examples",
    headers = [
        "FlatCombiningExamples.h",
    ],
    exported_deps = [
        "//folly/synchronization/test:flat_combining_examples",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "flat_combining_test_helpers",
    headers = [
        "FlatCombiningTestHelpers.h",
    ],
    exported_deps = [
        "//folly/synchronization/test:flat_combining_test_helpers",
    ],
)
