load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "test_main_demo",
    srcs = ["TestMainDemo.cpp"],
    test_main = "//folly/test/common:test_main_lib",
    deps = [
        "//folly:singleton",
    ],
)
