load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "test_main_demo",
    srcs = ["TestMainDemo.cpp"],
    test_main = "//folly/test/common:test_main_lib",
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//folly:singleton",
    ],
)
