load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fbcode_target(
    _kind = cpp_unittest,
    name = "test_main_demo",
    srcs = ["TestMainDemo.cpp"],
    test_main = "//folly/test/common:test_main_lib",
    deps = [
        "//folly:singleton",
    ],
)
