load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_benchmark.bzl", "fb_dirsync_cpp_benchmark")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_benchmark(
    name = "blake2xb_benchmark",
    srcs = ["Blake2xbBenchmark.cpp"],
    headers = [],
    deps = [
        "//folly:benchmark",
        "//folly:random",
        "//folly/crypto:blake2xb",
        "//folly/init:init",
        "//folly/io:iobuf",
    ],
)

fb_dirsync_cpp_unittest(
    name = "blake2xb_test",
    srcs = ["Blake2xbTest.cpp"],
    headers = [],
    deps = [
        "//folly:string",
        "//folly/crypto:blake2xb",
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "lt_hash_benchmark",
    srcs = [
        "LtHashBenchmark.cpp",
    ],
    headers = [],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:benchmark",
        "//folly:random",
        "//folly/crypto:lt_hash",
        "//folly/crypto:lt_hash_sse2",
        "//folly/init:init",
        "//folly/io:iobuf",
    ],
    external_deps = [
        ("libsodium", None, "sodium"),
    ],
)

fb_dirsync_cpp_benchmark(
    name = "lt_hash_benchmark_sse2",
    srcs = [
        "LtHashBenchmark.cpp",
    ],
    headers = [],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:benchmark",
        "//folly:random",
        "//folly/crypto:lt_hash_sse2",  # @manual
        "//folly/init:init",
        "//folly/io:iobuf",
    ],
    external_deps = [
        ("libsodium", None, "sodium"),
    ],
)

fb_dirsync_cpp_benchmark(
    name = "lt_hash_benchmark_avx2",
    srcs = [
        "LtHashBenchmark.cpp",
    ],
    headers = [],
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:benchmark",
        "//folly:random",
        "//folly/crypto:lt_hash_avx2",  # @manual
        "//folly/crypto:lt_hash_sse2",
        "//folly/init:init",
        "//folly/io:iobuf",
    ],
    external_deps = [
        ("libsodium", None, "sodium"),
    ],
)

fb_dirsync_cpp_unittest(
    name = "lt_hash_test",
    srcs = [
        "LtHashTest.cpp",
    ],
    headers = [],
    deps = [
        "//folly:random",
        "//folly:string",
        "//folly/crypto:lt_hash",
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "lt_hash_test_sse2",
    srcs = [
        "LtHashTest.cpp",
    ],
    headers = [],
    deps = [
        "//folly:random",
        "//folly:string",
        "//folly/crypto:lt_hash",
        "//folly/crypto:lt_hash_sse2",  # @manual
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "lt_hash_test_avx2",
    srcs = [
        "LtHashTest.cpp",
    ],
    headers = [],
    deps = [
        "//folly:random",
        "//folly:string",
        "//folly/crypto:lt_hash",
        "//folly/crypto:lt_hash_avx2",  # @manual
        "//folly/io:iobuf",
        "//folly/portability:gtest",
    ],
)
