extra_srcs = ["README.md", "md_doc/**/*.md"]
buildscript = []

[platform_fixup.'cfg(target_os = "macos")']
buildscript = []
rustc_flags = [
  "-lframework=IOKit",
  "-lframework=Foundation",
  "-lframework=CoreFoundation",
  "-lframework=DiskArbitration",
]
