load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fbcode_entropy_wardens_folly")

python_library(
    name = "co_bt",
    deps = [
        "//folly/coro/scripts:co_bt",
    ],
)
