load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "channel_processor_test",
    srcs = ["ChannelProcessorTest.cpp"],
    deps = [
        "//folly/channels:channel_processor",
        "//folly/executors:manual_executor",
        "//folly/portability:gmock",
    ],
)

fb_dirsync_cpp_unittest(
    name = "channel_test",
    srcs = ["ChannelTest.cpp"],
    labels = ["slow"],
    supports_static_listing = False,
    deps = [
        ":channel_test_util",
        "//folly/channels:channel",
        "//folly/coro:blocking_wait",
        "//folly/executors:manual_executor",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "fanout_channel_test",
    srcs = ["FanoutChannelTest.cpp"],
    deps = [
        ":channel_test_util",
        "//folly/channels:consume_channel",
        "//folly/channels:fanout_channel",
        "//folly/executors:manual_executor",
        "//folly/executors:serial_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "fanout_sender_test",
    srcs = ["FanoutSenderTest.cpp"],
    deps = [
        ":channel_test_util",
        "//folly/channels:consume_channel",
        "//folly/channels:fanout_sender",
        "//folly/executors:manual_executor",
        "//folly/executors:serial_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "max_concurrent_rate_limiter_test",
    srcs = [
        "MaxConcurrentRateLimiterTest.cpp",
    ],
    deps = [
        "//folly/channels:max_concurrent_rate_limiter",
        "//folly/executors:manual_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "merge_channel_test",
    srcs = [
        "MergeChannelTest.cpp",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        ":channel_test_util",
        "//folly/channels:consume_channel",
        "//folly/channels:merge_channel",
        "//folly/executors:manual_executor",
        "//folly/executors:serial_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "merge_test",
    srcs = ["MergeTest.cpp"],
    modifiers = ["ovr_config//project/folly/constraints:mobile[disabled]"],
    deps = [
        ":channel_test_util",
        "//folly/channels:consume_channel",
        "//folly/channels:merge",
        "//folly/executors:manual_executor",
        "//folly/executors:serial_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "multiplex_channel_test",
    srcs = ["MultiplexChannelTest.cpp"],
    deps = [
        ":channel_test_util",
        "//folly/channels:consume_channel",
        "//folly/channels:max_concurrent_rate_limiter",
        "//folly/channels:multiplex_channel",
        "//folly/coro:blocking_wait",
        "//folly/executors:manual_executor",
        "//folly/executors:serial_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "producer_test",
    srcs = ["ProducerTest.cpp"],
    deps = [
        ":channel_test_util",
        "//folly/channels:producer",
        "//folly/executors:manual_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "proxy_channel_test",
    srcs = ["ProxyChannelTest.cpp"],
    deps = [
        ":channel_test_util",
        "//folly/channels:proxy_channel",
        "//folly/executors:manual_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "transform_test",
    srcs = ["TransformTest.cpp"],
    deps = [
        ":channel_test_util",
        "//folly:scope_guard",
        "//folly:synchronized",
        "//folly/channels:consume_channel",
        "//folly/channels:max_concurrent_rate_limiter",
        "//folly/channels:transform",
        "//folly/coro:async_generator",
        "//folly/coro:detach_on_cancel",
        "//folly/executors:manual_executor",
        "//folly/executors:serial_executor",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_library(
    name = "channel_test_util",
    headers = ["ChannelTestUtil.h"],
    exported_deps = [
        "//folly/channels:consume_channel",
        "//folly/coro:detach_on_cancel",
        "//folly/coro:sleep",
        "//folly/executors:cpu_thread_pool_executor",
        "//folly/executors:io_thread_pool_executor",
        "//folly/executors:sequenced_executor",
        "//folly/futures:shared_promise",
        "//folly/portability:gmock",
    ],
)
