load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")

oncall("fbcode_entropy_wardens_folly")

python_unittest(
    name = "co_bt",
    srcs = ["co_bt.py"],
    deps = [
        "//folly/coro/scripts:co_bt",
    ],
)
