load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs:fb_python_test.bzl", "fb_python_test")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_rule.bzl", "fb_dirsync_rule")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_rule(
    name = "co_bt",
    srcs = ["co_bt.py"],
    fbcode_rule = python_unittest,
    xplat_rule = fb_python_test,
    deps = [
        "//folly/coro/scripts:co_bt",
    ],
)
