load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs:fb_python_test.bzl", "fb_python_test")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = fb_python_test,
    name = "co_bt",
    srcs = ["co_bt.py"],
    deps = [
        "//xplat/folly/coro/scripts:co_bt",
    ],
)

# !!!! fbcode/folly/coro/scripts/test/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = python_unittest,
    name = "co_bt",
    srcs = ["co_bt.py"],
    deps = [
        "//folly/coro/scripts:co_bt",
    ],
)
