load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "simd_any_of_test",
    srcs = [
        "SimdAnyOfTest.cpp",
    ],
    deps = [
        "//folly:range",
        "//folly/algorithm/simd/detail:simd_any_of",
        "//folly/algorithm/simd/detail:simd_platform",
        "//folly/container:span",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "simd_for_each_test",
    srcs = ["SimdForEachTest.cpp"],
    deps = [
        "//folly/algorithm/simd/detail:simd_for_each",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "traits_test",
    srcs = ["TraitsTest.cpp"],
    compiler_flags = ["--std=c++17"],
    deps = [
        "//folly/algorithm/simd/detail:traits",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

cpp_unittest(
    name = "unroll_utils_test",
    srcs = [
        "UnrollUtilsTest.cpp",
    ],
    deps = [
        "//folly/algorithm/simd/detail:unroll_utils",
        "//folly/portability:gtest",
    ],
)
