load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "unroll_utils_test",
    srcs = [
        "UnrollUtilsTest.cpp",
    ],
    deps = [
        "//folly/algorithm/simd/detail:unroll_utils",
        "//folly/portability:gtest",
    ],
)
