load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "x86",
    srcs = [],
    headers = ["x86.h"],
    feature = triage_InfrastructureSupermoduleOptou,
    use_raw_headers = True,
    exported_deps = [
        "//folly:portability",
    ],
)
