load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//xplat/folly:defs.bzl", "folly_xplat_cxx_library")
load("@fbsource//xplat/pfh/triage_InfrastructureSupermoduleOptou:DEFS.bzl", "triage_InfrastructureSupermoduleOptou")

oncall("fbcode_entropy_wardens_folly")

non_fbcode_target(
    _kind = folly_xplat_cxx_library,
    name = "openssl_session",
    srcs = ["OpenSSLSession.cpp"],
    feature = triage_InfrastructureSupermoduleOptou,
    raw_headers = ["OpenSSLSession.h"],
    exported_deps = [
        "//xplat/folly:portability_openssl",
        "//xplat/folly:shared_mutex",
        "//xplat/folly:synchronized",
        "//xplat/folly/ssl:openssl_ptr_types",
        "//xplat/folly/ssl:ssl_session",
    ],
)

# !!!! fbcode/folly/ssl/detail/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "openssl_session",
    srcs = ["OpenSSLSession.cpp"],
    headers = ["OpenSSLSession.h"],
    exported_deps = [
        "//folly:shared_mutex",
        "//folly:synchronized",
        "//folly/portability:openssl",
        "//folly/ssl:openssl_ptr_types",
        "//folly/ssl:ssl_session",
    ],
)
