load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "define_movable_deep_const_lref_copyable_test",
    srcs = ["DefineMovableDeepConstLrefCopyableTest.cpp"],
    deps = [
        "//folly/coro/safe/detail:define_movable_deep_const_lref_copyable",
        "//folly/portability:gtest",
    ],
)
