load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "stl_vector_test",
    srcs = ["StlVectorTest.cpp"],
    labels = ["slow"],
    deps = [
        "//folly:conv",
        "//folly:fbvector",
        "//folly:portability",
        "//folly:scope_guard",
        "//folly/chrono:hardware",
        "//folly/lang:pretty",
        "//folly/portability:gflags",
        "//folly/portability:gtest",
        "//folly/test:test_utils",
    ],
    external_deps = [
        "boost",
        ("boost", None, "boost_preprocessor"),
    ],
)
