load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

# xplat unit tests

fb_dirsync_cpp_unittest(
    name = "apply_tuple_test",
    srcs = ["ApplyTupleTest.cpp"],
    deps = [
        "//folly:overload",
        "//folly/functional:apply_tuple",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "invoke_test",
    srcs = ["InvokeTest.cpp"],
    deps = [
        "//folly/functional:invoke",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "partial_test",
    srcs = ["PartialTest.cpp"],
    deps = [
        "//folly:function",
        "//folly/functional:partial",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "protocol_test",
    srcs = ["protocol_test.cpp"],
    deps = [
        "//folly/functional:protocol",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "traits_test",
    srcs = ["traits_test.cpp"],
    deps = [
        "//folly/functional:traits",
        "//folly/portability:gtest",
    ],
)

# fbcode unit tests
