load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "graph_cycle_detector",
    headers = [
        "GraphCycleDetector.h",
    ],
    exported_deps = [
        "//folly/observer/detail:graph_cycle_detector",
    ],
)

cpp_library(
    name = "observer_manager",
    headers = [
        "Core.h",
        "ObserverManager.h",
    ],
    exported_deps = [
        "//folly/observer/detail:observer_manager",
    ],
)
