load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_benchmark.bzl", "fb_dirsync_cpp_benchmark")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_unittest.bzl", "fb_dirsync_cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_unittest(
    name = "hex_test",
    srcs = ["hex_test.cpp"],
    deps = [
        "//folly:likely",
        "//folly/codec:hex",
        "//folly/lang:keep",
        "//folly/portability:gmock",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_unittest(
    name = "uuid_test",
    srcs = ["UuidTest.cpp"],
    supports_static_listing = False,
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:random",
        "//folly/codec:uuid",
        "//folly/portability:gtest",
    ],
)

fb_dirsync_cpp_benchmark(
    name = "uuid_benchmark",
    srcs = ["UuidBenchmark.cpp"],
    compiler_flags = ["-flto"],
    deps = [
        "//folly:benchmark",
        "//folly/codec:uuid",
    ],
    external_deps = [
        ("boost", None, "boost_lexical_cast"),
        ("boost", None, "boost_uuid"),
        ("util-linux", None, "uuid"),
    ],
)
