load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_rule.bzl", "fb_dirsync_rule")

oncall("rust_libraries")

fb_dirsync_rule(
    name = "folly_compression",
    srcs = ["compression.rs"],
    cpp_deps = [":compression-ffi"],
    crate_root = "compression.rs",
    cxx_bridge = "compression.rs",
    fbcode_rule = rust_library,
    modifiers = ["ovr_config//project/folly/constraints:mobile[disabled]"],
    deps = [
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:cxx",
        "fbsource//third-party/rust:thiserror",
        "fbsource//xplat/folly/rust/iobuf:iobuf",
    ],
)

fb_dirsync_cpp_library(
    name = "compression-ffi",
    srcs = ["compression.cpp"],
    headers = ["compression.h"],
    preferred_linkage = "static",
    exported_deps = [
        "fbsource//third-party/rust:cxx-core",
        "//folly/compression:compression",
        "//folly/io:iobuf",
    ],
)
