load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "test_util_demo",
    srcs = ["TestUtils.cpp"],
    headers = [],
    deps = [
        "//folly/portability:gtest",
        "//folly/test:test_utils",
    ],
)
