load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "malloc_impl",
    srcs = ["MallocImpl.cpp"],
    headers = ["MallocImpl.h"],
    use_raw_headers = True,
    exported_deps = ["//folly:portability"],
)
