load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fbcode_entropy_wardens_folly")

cpp_library(
    name = "malloc_impl",
    srcs = ["MallocImpl.cpp"],
    headers = ["MallocImpl.h"],
    exported_deps = ["//folly:portability"],
)
