load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fbcode_entropy_wardens_folly")

cpp_unittest(
    name = "atomic_queue_test",
    srcs = [
        "AtomicQueueTest.cpp",
    ],
    deps = [
        "//folly/experimental/channels/detail:atomic_queue",
        "//folly/portability:gtest",
        "//folly/synchronization:baton",
    ],
)

cpp_unittest(
    name = "pointer_variant_test",
    srcs = [
        "PointerVariantTest.cpp",
    ],
    deps = [
        "//folly/experimental/channels/detail:pointer_variant",
        "//folly/portability:gtest",
    ],
)
