load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")
load(
    "../defs.bzl",
    "CXXFLAGS",
    "folly_xplat_library",
)

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "async_trace",
    srcs = ["AsyncTrace.cpp"],
    headers = ["AsyncTrace.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:optional",
    ],
)

fb_dirsync_cpp_library(
    name = "atomic_hash_utils",
    headers = ["AtomicHashUtils.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/portability:asm",
    ],
)

fb_dirsync_cpp_library(
    name = "atomic_unordered_map_utils",
    headers = ["AtomicUnorderedMapUtils.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:exception",
        "//folly/portability:sys_mman",
        "//folly/portability:unistd",
    ],
)

fb_dirsync_cpp_library(
    name = "avx2",
    srcs = ["Avx2.cpp"],
    headers = ["Avx2.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:cpp_attributes",
        "//folly:portability",
    ],
)

fb_dirsync_cpp_library(
    name = "discriminated_ptr_detail",
    headers = ["DiscriminatedPtrDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/functional:invoke",
    ],
)

fb_dirsync_cpp_library(
    name = "file_util_detail",
    srcs = ["FileUtilDetail.cpp"],
    headers = ["FileUtilDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly/portability:config",
    ],
    exported_deps = [
        "//folly/portability:sys_types",
    ],
)

fb_dirsync_cpp_library(
    name = "file_util_vector_detail",
    headers = ["FileUtilVectorDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":file_util_detail",
        "//folly/portability:sys_uio",
        "//folly/portability:unistd",
    ],
)

fb_dirsync_cpp_library(
    name = "fingerprint_polynomial",
    headers = ["FingerprintPolynomial.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
)

fb_dirsync_cpp_library(
    name = "group_varint_detail",
    headers = ["GroupVarintDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
)

fb_dirsync_cpp_library(
    name = "ip_address",
    srcs = ["IPAddress.cpp"],
    headers = ["IPAddress.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly/portability:fmt_compile",
    ],
    exported_deps = [
        "//folly/portability:sockets",
    ],
)

fb_dirsync_cpp_library(
    name = "ip_address_source",
    headers = ["IPAddressSource.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/glog:glog",
        ":ip_address",
    ],
)

fb_dirsync_cpp_library(
    name = "memory_idler",
    srcs = ["MemoryIdler.cpp"],
    headers = ["MemoryIdler.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:glog",
        "//folly:portability",
        "//folly:scope_guard",
        "//folly/concurrency:cache_locality",
        "//folly/memory:mallctl_helper",
        "//folly/memory:malloc",
        "//folly/portability:gflags",
        "//folly/portability:pthread",
        "//folly/portability:sys_mman",
        "//folly/portability:unistd",
        "//folly/system:pid",
    ],
    exported_deps = [
        ":futex",
        "//folly/hash:hash",
        "//folly/synchronization:atomic_struct",
        "//folly/system:thread_id",
    ],
)

fb_dirsync_cpp_library(
    name = "mpmc_pipeline_detail",
    headers = ["MPMCPipelineDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:mpmc_queue",
    ],
)

fb_dirsync_cpp_library(
    name = "perf_scoped",
    srcs = ["PerfScoped.cpp"],
    headers = ["PerfScoped.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    # folly subprocess is not supported on windows
    deps = [
        "//folly:conv",
        "//folly/system:pid",
        "//folly/testing:test_util",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": ["//folly:subprocess"],
    }),
    external_deps = [
        ("boost", None, "boost_regex"),
    ],
)

fb_dirsync_cpp_library(
    name = "poly_detail",
    headers = ["PolyDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":typelist",
        "//folly:poly_exception",
        "//folly:portability",
        "//folly:traits",
        "//folly:utility",
        "//folly/functional:invoke",
        "//folly/lang:exception",
        "//folly/lang:static_const",
    ],
)

fb_dirsync_cpp_library(
    name = "simple_simd_string_utils",
    srcs = ["SimpleSimdStringUtils.cpp"],
    headers = [
        "SimpleSimdStringUtils.h",
        "SimpleSimdStringUtilsImpl.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:range",
        "//folly/algorithm/simd/detail:simd_any_of",
        "//folly/algorithm/simd/detail:simd_platform",
    ],
)

fb_dirsync_cpp_library(
    name = "singleton",
    headers = ["Singleton.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:traits",
    ],
)

fb_dirsync_cpp_library(
    name = "slow_fingerprint",
    headers = ["SlowFingerprint.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        ":fingerprint_polynomial",
        "//folly:fingerprint",
        "//folly:range",
    ],
)

fb_dirsync_cpp_library(
    name = "socket_fast_open",
    srcs = ["SocketFastOpen.cpp"],
    headers = ["SocketFastOpen.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly/net:network_socket",
        "//folly/portability:sockets",
    ],
)

fb_dirsync_cpp_library(
    name = "split_string_simd",
    headers = [
        "SplitStringSimd.h",
        "SplitStringSimdImpl.h",
    ],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:portability",
        "//folly:range",
        "//folly/algorithm/simd:ignore",
        "//folly/algorithm/simd:movemask",
        "//folly/algorithm/simd/detail:simd_for_each",
        "//folly/algorithm/simd/detail:simd_platform",
        "//folly/lang:bits",
    ],
)

fb_dirsync_cpp_library(
    name = "sse",
    srcs = ["Sse.cpp"],
    headers = ["Sse.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:cpp_attributes",
        "//folly:portability",
    ],
)

fb_dirsync_cpp_library(
    name = "thread_local_detail",
    srcs = ["ThreadLocalDetail.cpp"],
    headers = ["ThreadLocalDetail.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        ":thread_local_globals",
        "//folly:constexpr_math",
        "//folly:utility",
        "//folly/hash:murmur_hash",
        "//folly/lang:hint",
        "//folly/memory:sanitize_leak",
        "//folly/random:hash",
        "//folly/synchronization:call_once",
    ],
    exported_deps = [
        "fbsource//third-party/glog:glog",
        ":static_singleton_manager",
        ":unique_instance",
        "//folly:exception",
        "//folly:function",
        "//folly:map_util",
        "//folly:portability",
        "//folly:scope_guard",
        "//folly:shared_mutex",
        "//folly:synchronized",
        "//folly/concurrency/container:atomic_grow_array",
        "//folly/container:foreach",
        "//folly/lang:exception",
        "//folly/memory:malloc",
        "//folly/portability:pthread",
        "//folly/synchronization:micro_spin_lock",
        "//folly/synchronization:relaxed_atomic",
        "//folly/system:at_fork",
        "//folly/system:thread_id",
    ],
)

fb_dirsync_cpp_library(
    name = "thread_local_globals",
    srcs = ["thread_local_globals.cpp"],
    headers = ["thread_local_globals.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        ":static_singleton_manager",
        "//folly/lang:exception",
        "//folly/portability:pthread",
    ],
)

fb_dirsync_cpp_library(
    name = "turn_sequencer",
    headers = ["TurnSequencer.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "fbsource//third-party/glog:glog",
        ":futex",
        "//folly:portability",
        "//folly/chrono:hardware",
        "//folly/portability:asm",
        "//folly/portability:unistd",
    ],
)

fb_dirsync_cpp_library(
    name = "tuple",
    headers = ["tuple.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:cpp_attributes",
        "//folly:traits",
        "//folly/lang:safe_alias_fwd",
    ],
)

fb_dirsync_cpp_library(
    name = "typelist",
    headers = ["TypeList.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    exported_deps = [
        "//folly:traits",
        "//folly:utility",
    ],
)

fb_dirsync_cpp_library(
    name = "unique_instance",
    srcs = ["UniqueInstance.cpp"],
    headers = ["UniqueInstance.h"],
    use_raw_headers = True,
    xplat_impl = folly_xplat_library,
    deps = [
        "//folly:demangle",
        "//folly/lang:exception",
    ],
    exported_deps = [
        ":static_singleton_manager",
        "//folly:cpp_attributes",
    ],
)

# Targets below are kept as dual fbcode_target/non_fbcode_target patterns
# because they have complex attributes that fb_dirsync_cpp_library doesn't handle:
# - futex, iterators: compiler_flags on xplat side
# - range_common, range_simd, range_sse42: undefined_symbols on fbcode side
# - static_singleton_manager: force_static = select() on xplat side
# - traponavx512: arch_preprocessor_flags (fbcode) vs compiler_flags + CXXFLAGS (xplat)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "futex",
    srcs = [
        "Futex.cpp",
    ],
    compiler_flags = [
        "-fno-omit-frame-pointer",
    ],
    raw_headers = [
        "Futex.h",
        "Futex-inl.h",
    ],
    exported_deps = [
        "fbsource//xplat/folly/hash:hash",
        "fbsource//xplat/folly/portability:sys_syscall",
        "fbsource//xplat/folly/portability:unistd",
        "fbsource//xplat/folly/synchronization:parking_lot",
        "//xplat/folly:scope_guard",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "futex",
    srcs = ["Futex.cpp"],
    headers = [
        "Futex.h",
        "Futex-inl.h",
    ],
    deps = [
        "//folly:scope_guard",
        "//folly/hash:hash",
        "//folly/portability:sys_syscall",
    ],
    exported_deps = [
        "//folly/synchronization:parking_lot",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "iterators",
    compiler_flags = [
        "-fno-omit-frame-pointer",
    ],
    raw_headers = [
        "Iterators.h",
    ],
    exported_deps = [
        "fbsource//xplat/folly/portability:sys_types",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "iterators",
    headers = ["Iterators.h"],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "range_common",
    srcs = [
        "RangeCommon.cpp",
    ],
    raw_headers = [
        "RangeCommon.h",
    ],
    deps = [
        "//xplat/folly:likely",
        "//xplat/folly/container:sparse_byte_set",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "range_common",
    srcs = ["RangeCommon.cpp"],
    headers = ["RangeCommon.h"],
    undefined_symbols = True,  # TODO(T23121628): fix deps and remove
    deps = [
        "//folly/container:sparse_byte_set",
    ],
    exported_deps = [
        "//folly:likely",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "range_simd",
    srcs = [
        "RangeSimd.cpp",
    ],
    raw_headers = [
        "RangeSimd.h",
    ],
    deps = [
        ":range_sse42",
        "//xplat/folly:likely",
        "//xplat/folly:portability",
        "//xplat/folly/detail:range_common",
        "//xplat/folly/external/nvidia/detail:range_sve2",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "range_simd",
    srcs = ["RangeSimd.cpp"],
    headers = ["RangeSimd.h"],
    undefined_symbols = True,
    deps = [
        ":range_sse42",
        "//folly:portability",
        "//folly/external/nvidia/detail:range_sve2",
    ],
    exported_deps = [
        ":range_common",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "range_sse42",
    srcs = [
        "RangeSse42.cpp",
    ],
    raw_headers = [
        "RangeSse42.h",
    ],
    deps = [
        "//xplat/folly:likely",
        "//xplat/folly:portability",
        "//xplat/folly/detail:range_common",
        "//xplat/folly/detail:sse",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "range_sse42",
    srcs = ["RangeSse42.cpp"],
    headers = ["RangeSse42.h"],
    undefined_symbols = True,  # TODO(T23121628): fix deps and remove
    deps = [
        ":sse",
        "//folly:likely",
        "//folly:portability",
    ],
    exported_deps = [
        ":range_common",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "static_singleton_manager",
    srcs = [
        "StaticSingletonManager.cpp",
    ],
    force_static = bool(select({
        "DEFAULT": False,
        "ovr_config//os:macos": True,
    })),
    raw_headers = [
        "StaticSingletonManager.h",
    ],
    deps = [
        "//xplat/folly:c_portability",
        "//xplat/folly:indestructible",
        "//xplat/folly:likely",
        "//xplat/folly:utility",
        "//xplat/folly/detail:singleton",
        "//xplat/folly/lang:thunk",
        "//xplat/folly/lang:type_info",
        "//xplat/folly/memory:reentrant_allocator",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "static_singleton_manager",
    srcs = ["StaticSingletonManager.cpp"],
    headers = ["StaticSingletonManager.h"],
    deps = [
        "//folly/memory:reentrant_allocator",
    ],
    exported_deps = [
        ":singleton",
        "//folly:c_portability",
        "//folly:indestructible",
        "//folly:likely",
        "//folly:utility",
        "//folly/lang:thunk",
        "//folly/lang:type_info",
    ],
)

non_fbcode_target(
    _kind = folly_xplat_library,
    name = "traponavx512",
    srcs = ["TrapOnAvx512.cpp"],
    compiler_flags = CXXFLAGS + select({
        "DEFAULT": [],
        "ovr_config//toolchain/fb:fbcode-x86_64": [
            "-msse4.2",
            "-mavx512f",
            "-mavx512vl",
        ],
    }),
    raw_headers = ["TrapOnAvx512.h"],
    deps = [
        "//xplat/folly:portability",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "traponavx512",
    srcs = ["TrapOnAvx512.cpp"],
    headers = ["TrapOnAvx512.h"],
    compiler_flags = select({
        "DEFAULT": [],
        "ovr_config//cpu:x86_64": [
            "-msse4.2",
            "-mavx512f",
            "-mavx512vl",
        ],
    }),
    deps = [
        "//folly:portability",
    ],
)
