load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_binary.bzl", "fb_dirsync_cpp_binary")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_binary(
    name = "benchmark_compare",
    srcs = ["BenchmarkCompare.cpp"],
    deps = [
        "//folly:benchmark",
        "//folly:file_util",
        "//folly/init:init",
        "//folly/json:dynamic",
    ],
)
