load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "init_thread_factory",
    headers = ["InitThreadFactory.h"],
    use_raw_headers = True,
    exported_deps = [
        ":thread_factory",
        "//folly:scope_guard",
    ],
)

fb_dirsync_cpp_library(
    name = "priority_thread_factory",
    srcs = ["PriorityThreadFactory.cpp"],
    headers = ["PriorityThreadFactory.h"],
    use_raw_headers = True,
    deps = [
        "fbsource//third-party/glog:glog",
        "//folly:string",
        "//folly/portability:sys_resource",
        "//folly/portability:sys_time",
        "//folly/system:thread_name",
    ],
    exported_deps = [
        ":init_thread_factory",
    ],
)

fb_dirsync_cpp_library(
    name = "thread_factory",
    headers = ["ThreadFactory.h"],
    use_raw_headers = True,
    exported_deps = [
        "//folly:executor",
    ],
)

fb_dirsync_cpp_library(
    name = "named_thread_factory",
    headers = ["NamedThreadFactory.h"],
    use_raw_headers = True,
    exported_deps = [
        ":thread_factory",
        "//folly:conv",
        "//folly:range",
        "//folly/system:thread_name",
    ],
)
