load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbsource//tools/build_defs/dirsync:fb_dirsync_cpp_library.bzl", "fb_dirsync_cpp_library")

oncall("fbcode_entropy_wardens_folly")

fb_dirsync_cpp_library(
    name = "atomic_queue",
    headers = [
        "AtomicQueue.h",
    ],
    use_raw_headers = True,
    exported_deps = [
        "fbsource//third-party/glog:glog",
        "//folly/lang:assume",
    ],
)

fb_dirsync_cpp_library(
    name = "channel_bridge",
    headers = ["ChannelBridge.h"],
    use_raw_headers = True,
    exported_deps = [
        "//folly:try",
        "//folly/experimental/channels/detail:atomic_queue",
    ],
)

# !!!! fbcode/folly/channels/detail/TARGETS was merged into this file, see https://fburl.com/workplace/xl8l9yuo for more info !!!!

fbcode_target(
    _kind = cpp_library,
    name = "intrusive_ptr",
    headers = ["IntrusivePtr.h"],
    exported_external_deps = [
        "boost",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "multiplexer_traits",
    headers = ["MultiplexerTraits.h"],
    exported_deps = [
        "//folly:traits",
        "//folly/functional:traits",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "pointer_variant",
    headers = ["PointerVariant.h"],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "//folly:demangle",
    ],
)

fbcode_target(
    _kind = cpp_library,
    name = "utility",
    headers = [
        "Utility.h",
    ],
    exported_deps = [
        "//folly:exception_wrapper",
        "//folly:function",
        "//folly:scope_guard",
        "//folly/channels:channel",
        "//folly/channels:rate_limiter",
        "//folly/coro:promise",
        "//folly/coro:task",
        "//folly/executors:sequenced_executor",
    ],
)
